### ISSUE TITLE
Downloading GraphQL Hive's Router returns 503

### ISSUE THREAD

**Issue by wcole1-godaddy** [kamilkisiela/graphql-hive#1004]
When downloading GraphQL Hive's router, I'm getting a 503 error.

`curl -fsSL https://graphql-hive.com/apollo-router-download.sh | bash`

Error: `curl: (22) The requested URL returned error: 503`

**Comment by kamilkisiela** [comment]
Ok, it's fixed now

**Comment by wcole1-godaddy** [comment]
Works, thanks!
