### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by ArcaneDiver** [kamilkisiela/graphql-hive#1056]
Hi, i know that the title of the issue is generic...

The project is interesting but I couldn't help but notice that 1.x has not been released.
I would also like to run this in combo with mesh, which is also still at 0.x.x, but it has a roadmap to 1.x.

My question is: is there any reason because the project isn't stable enough to reach 1.x.
I haven't found any reference in the roadmap about stable release.

It is also true that Guild is selling the product as a saas...

I apologize in advance if a similar issue has already been created.

**Comment by kamilkisiela** [comment]
If you want I can release v2 :) It's just a version number.

We collect billions of GraphQL Requests monthly, so it's production ready for almost 2 years.

**Comment by dotansimha** [comment]
@kamilkisiela it might be good timing to release v1 for the client/cli? 😄

**Comment by ArcaneDiver** [comment]
Ok, it's just to my company standards, my ops manager even before take a look to the project, dont accept anything thats under 1.x 😢

**Comment by dotansimha** [comment]
> Ok, it's just to my company standards, my ops manager even before take a look to the project, dont accept anything thats under 1.x 😢

We might release v1 of the npm libraries, but when it comes to the self-hosting option, we are using Docker tags based on commit IDs, and don't follow official numeric versioning. 

I am closing this for now.
