### ISSUE TITLE
Provide a way to preview all clients and their versions

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#1060]
### Discussed in https://github.com/kamilkisiela/graphql-hive/discussions/1002

<div type='discussions-op-text'>

<sup>Originally posted by **cookieMr** January 13, 2023</sup>
https://docs.graphql-hive.com/features/monitoring#using-dashboard

On the dashboard in `Clients` section i can see two charts. for Top 5 most common consumers.
Can you provide a way to preview all `Other clients` (all cients) and all `Other versions` (all versions)? (on a separate window/pop up/whatever makes sense to you guys)

![image](https://user-images.githubusercontent.com/8577083/212306622-a5539665-e147-4e79-975b-244fb6141002.png)
</div>

**Comment by kamilkisiela** [comment]
I can imagine a Drawer component that slides from the right side and displays a table. Why table? If there are too many clients, the chart will look weird.

**Comment by cookieMr** [comment]
For my specific case is that we use an HTTP header that user sends to check which version is doing a call to our GraphQL endpoint. On the picture you can see that we have 1.7k versions and we are unable to quickly check them (in Hive; we can do some splunk/grafana queries).

The thing is that these 1.7k might be invalid values send by malicious actor and we would like to know what kind of values is he/she sending in a header that we use for versioning. Maybe we can block some of his/her requests based on this header. But for that we would like to see easily these versions.
