### ISSUE TITLE
Can I use “Monitoring Operations” with URQL?

### ISSUE THREAD

**Issue by nandorojo** [kamilkisiela/graphql-hive#1122]
Can I use this with URQL? I see there is an Apollo plugin, but no mention of URQL. Thanks!

https://docs.graphql-hive.com/features/monitoring

**Comment by nandorojo** [comment]
ah, makes sense! thanks for clarifying!

**Comment by jerber** [comment]
@dotansimha I see you don't have a python sdk. Is there an API spec to upload the raw GQL data such that I could build one?

**Comment by dotansimha** [comment]
> @dotansimha I see you don't have a python sdk. Is there an API spec to upload the raw GQL data such that I could build one?

At the moment we do not have one, but maybe it is worth keeping an eye on this one: https://github.com/kamilkisiela/graphql-hive/issues/1122#issuecomment-1402381597 (and please share your stack and setup, it might help us to prioritize!)

**Comment by retreatpartner** [comment]
@jerber did you build one for yourself? :)

**Comment by nandorojo** [comment]
I don’t believe we did.
