### ISSUE TITLE
Assigning an organization for Okta Users

### ISSUE THREAD

**Issue by rperryng** [kamilkisiela/graphql-hive#1160]
Hello

I recently enabled the okta integration for our hosted hive application.

Maybe I am missing something, but is there a way to assign all users to the same "organization"?  as of now, it seems new users get assigned to their own organization and so all the existing projects/environments we had set up are not shared for each okta user.

**Comment by rperryng** [comment]
Thanks @n1ru4l, I definitely made that mistake, sorry 😅 ...

I have set `AUTH_ORGANIZATION_OIDC` to 1 but when viewing my settings page the "Connect OpenID Connect Provider" button seems to be missing.  I also verified this behaviour when running locally with the [community image @ `ab38a700e`](https://github.com/kamilkisiela/graphql-hive/blob/ab38a700ee34b8443bc3b56b6074070dfe7067ad/docker/docker-compose.community.yml) which has that setting enabled by default

![image](https://user-images.githubusercontent.com/6402435/215576102-8acd403f-a8ee-4313-b2da-15fe1109a928.png)

I also tried visiting `https://$BASE_URL/$ORG/view/settings#manage-oidc-integration` directly as the guide suggests but it just took me to the empty settings page.  Is there another thing I have missed (If so, sorry in advance!! 😅 ...)?

**Comment by n1ru4l** [comment]
@rperryng Did you make sure that the containers are running with the new environment variables? You can execute `printenv` within the container to check. If you ran `docker compose up`, without prior running `docker compose down`. The up command will re-use the old containers with the old environment variables.

Aside from that you can run `docker compose up --force-recreate` to make sure the containers are recreated with the new variables.

**Comment by rperryng** [comment]
@n1ru4l Yeah, I am confident that our hosted instance is running with `AUTH_ORGANIZATION_OIDC` set to `1` for our `app` and `server` containers (actually, all of our `graphql-hive-*` containers have it enabled, was just easier that way... 😇).

And yeah I also double checked with my local deployment that the flag was enabled for those containers as well.  Actually, the community image is already pre-configured with `AUTH_ORGANIZATION_OIDC` enabled for the [app](https://github.com/kamilkisiela/graphql-hive/blob/0d0570032da3ba3896022a426a9d59fa6c101407/docker/docker-compose.community.yml#L379) and [server](https://github.com/kamilkisiela/graphql-hive/blob/0d0570032da3ba3896022a426a9d59fa6c101407/docker/docker-compose.community.yml#L252) containers, I would have had to go out of my way to disable it I believe!

I have a very short but detailed video showing the entire process from scratch (generating the compose file and deleting all mounted volumes): https://www.youtube.com/watch?v=btmtQO0R1ls . I used the latest commit ([`0d05700`](https://github.com/kamilkisiela/graphql-hive/tree/0d0570032da3ba3896022a426a9d59fa6c101407) at the time).

In the video I show that my generated `docker-compose.with-env.yml` file ([link for reference](https://gist.github.com/rperryng/b5ce6ee6a0f783cfd6b2303e8c318af9#file-docker-compose-with-env-yml)) has the ENV var set in via `yq` expressions.  I also show starting up the `app`/`server` containers (`docker compose -f docker-compose.with-env.yml run app /bin/sh`) and use `printenv` to verify the values as well.

**Comment by n1ru4l** [comment]
@rperryng Oh, I think I know what this issue is. When you first log into Hive a personal organization that is scoped to your user will be created. In this organization, you cannot add external users.

You first need to create a new organization:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/14338007/216069928-ca9ce808-cc72-46f8-abad-3a1c78ee9b37.png">

Then it should be visible!

<img width="784" alt="image" src="https://user-images.githubusercontent.com/14338007/216070077-389bb568-e29f-4727-ad81-2b81171d889b.png">

Sorry for the inconvenience.

We are already debating on completely removing the concept of a personal organization.

**Comment by rperryng** [comment]
Aha! that was it, thank you for the pointer.
