### ISSUE TITLE
Windows installation - GraphQL hive fail to run

### ISSUE THREAD

**Issue by fmorissette-equisoft** [kamilkisiela/graphql-hive#1226]
### Discussed in https://github.com/kamilkisiela/graphql-hive/discussions/1214

<div type='discussions-op-text'>

<sup>Originally posted by **fmorissette-equisoft** February  1, 2023</sup>
Can someone help me to figure out if graphql-hive cli is properly supported on Windows ?
This is the error i'm getting : 

throw new Error("Service '" + name + "' not found in architect app!");
^
Error: Service 'cli' not found in architect app!
    at Architect.getService 

Thanks !</div>

**Comment by dotansimha** [comment]
@n1ru4l @kamilkisiela any idea how can we try to test/reproduce/fix?

**Comment by n1ru4l** [comment]
@dotansimha We can run the CLI on a GitHub action windows runner.

**Comment by casey-chow** [comment]
I'm able to reproduce this on mac right now.
