### ISSUE TITLE
Schema:publish detects errors on valid schema

### ISSUE THREAD

**Issue by s-af** [kamilkisiela/graphql-hive#1255]
Hi!

I am experimenting with hive for Federation v2 and found some issues with checking/publishing. 

Steps to reproduce:
1. Create new project https://app.graphql-hive.com/ with type "federation"
2. Go to any target and generate Registry Access Token and CDN Access Token
3. Setup and configure external composition using [pre-build docker image](https://docs.graphql-hive.com/features/external-schema-composition#pre-built-docker-image)
4. Create schema-a.graphql file:
    ```
    extend schema @link(url: "https://specs.apollo.dev/federation/v2.0",
        import: ["@key", "@shareable", "@inaccessible", "@override", "@external", "@requires", "@provides", "@tag"])
    
    type Query {
        someQuery: SomeQueryResponse
    }
    
    type SomeQueryResponse @key(fields: "id") {
        id: ID!
        data: String!
    }
    ```
5. Publish initial schema 
    ```
    hive schema:publish --author author --commit commit --force --service schema-a --url http://host.docker.internal:8081/graphql ./schema-a.graphql
    ```
6. Configure and run [Apollo Router](https://docs.graphql-hive.com/features/monitoring#apollo-router) with simple configuration:
      ```
      supergraph:
        listen: 0.0.0.0:4000
      plugins:
        hive.usage:
          {}
      ```
7. Open router on port 4000 and verify schema explorer has query: _**someQuery: SomeQueryResponse**_
8. Modify schema and add some breaking changes
      ```
      extend schema @link(url: "https://specs.apollo.dev/federation/v2.0",
          import: ["@key", "@shareable", "@inaccessible", "@override", "@external", "@requires", "@provides", "@tag"])
      
      type Query {
          someQuery: SomeQueryResponse
          oneMoreQuery: OneMoreQueryResponse
      }
      
      type SomeQueryResponse @key(fields: "id") {
          id: ID!
          data: String! @external
      }
      
      type OneMoreQueryResponse {
          data: String!
      }
      ```
9. Publish schema. Hive will detect errors in schema.
10. Modify schema file and make it valid by removing **@external** 
```
extend schema @link(url: "https://specs.apollo.dev/federation/v2.0",
    import: ["@key", "@shareable", "@inaccessible", "@override", "@external", "@requires", "@provides", "@tag"])

type Query {
    someQuery: SomeQueryResponse
    oneMoreQuery: OneMoreQueryResponse
}

type SomeQueryResponse @key(fields: "id") {
    id: ID!
    data: String!
}

type OneMoreQueryResponse {
    data: String!
}
```
11. Publish schema

After _hive schema:publish_ I was able to see error in console:
```
× Detected 1 error

   - Failed to compare schemas: Failed to build schema: Schemas couldn't be merged:
         - [schema-a] Field SomeQueryResponse.data is marked @external but is not used in any federation directive (@key, @provides, @requires) or to satisfy an interface; the field declaration has no u
se and should be removed (or the field should not be @external).

```
In app.graphql-hive.com -> Project -> Target -> History graphql schema build marked as failed.
In Apollo Router query explorer I was not able to find **_oneMoreQuery: OneMoreQueryResponse_**.

Rerunning _hive schema:publish_ again returns same error.

Rerunning _hive schema:publish_ after some time (~10 mins) return success with message "√ No changes. Skipping.", but graphql schema build still marked as failed.

**Comment by dotansimha** [comment]
@kamilkisiela can you please take a look?

**Comment by kamilkisiela** [comment]
My guess is that it's related to Federation v2. We advise using https://docs.graphql-hive.com/features/external-schema-composition#pre-built-docker-image for Federation v2.

**Comment by kamilkisiela** [comment]
We're releasing a new model of Schema Registry that should fix it.

**Comment by kamilkisiela** [comment]
It should work now, try again.

**Comment by s-af** [comment]
thanks, will check

**Comment by s-af** [comment]
Now it work
