### ISSUE TITLE
CLI: missing graphql dependency

### ISSUE THREAD

**Issue by stayallive** [kamilkisiela/graphql-hive#131]
Hello, when running `hive schema:publish /path/to/schema` I get the following error:

```
 ❯ hive schema:publish
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /path/to/project/node_modules/@graphql-hive/cli/dist/commands/schema/publish.js
 ›   Code: MODULE_NOT_FOUND

 ❯ hive --version
@graphql-hive/cli/0.14.6 darwin-arm64 node-v16.13.0
```

I have no clue what is happening here... I have installed `"@graphql-hive/cli": "^0.14.6"` as a dev dependency using Yarn. Ran `yarn install` and even `yarn upgrade` to see if that changes anything but no. Also tried version `0.13.0` but that didn't make a difference.

The file mentioned in the error exists on disk and looks complete enough.

It's also not only for schema:publish but for any command, I can execute `hive schema` en see the help for the available commands but any actual command is throwing a similar error with the exception for `hive update` and `hive help` which seem to function correctly.

Any clue what I'm missing here?

**Comment by kamilkisiela** [comment]
Could you provide a reproduction? I tried to reproduce it here https://github.com/kamilkisiela/graphql-hive-repro/runs/6739666027?check_suite_focus=true and it works, the modules are loaded, the GraphQL request is made.

**Comment by kfirdado** [comment]
Had the same issue - needed to install graphql module manually as it is defined as peerDependency and not installed by default.

**Comment by kamilkisiela** [comment]
Let's decide if we want to make `graphql` peer or direct dependency #162

**Comment by kamilkisiela** [comment]
`graphql` dependency is now part of CLI, starting with v0.17.0

**Comment by stayallive** [comment]
Great! Thanks!
