### ISSUE TITLE
Resolvable not supported FederationV2 when checking the subgraph  

### ISSUE THREAD

**Issue by fmorissette-equisoft** [kamilkisiela/graphql-hive#1330]
I started up to generate FederationV2 compatible subgraphs but now hive-cli started up to return the following:
 **Unknown argument resolvable on directive @key**

Any idea on this ?

**Comment by kamilkisiela** [comment]
It's probably because it's not backwards-compatible with Federation v1, so unfortunately you need to use 
https://docs.graphql-hive.com/features/external-schema-composition#pre-built-docker-image to compose subgraphs for Federation v2. It will be supported natively soon.

**Comment by fmorissette-equisoft** [comment]
Great. Thanks. That's the only issue i'm having. Otherwise just removing this attribute is functional
