### ISSUE TITLE
extractFederationServiceSDL not removing _entities in Federation V2 

### ISSUE THREAD

**Issue by aeckard** [kamilkisiela/graphql-hive#1350]
Hello

When using the `@graphql-hive/client` package to publish a schema to a self-hosted Hive for a Federation V2 subgraph service (using the `composition-federation-2` Docker image), it publishes an invalid schema with the following error.

```
Failed to build schema: Schemas couldn't be merged:
	 - [servicename] Unknown type _Any
```

It appears this occurs because `scalar _Any` is stripped, but `Query._entities` is not. Its definition looks like this:
```
_entities(representations:[_Any!]!):[_Entity]!
```

Since `_Any` is not defined as a Scalar, it is unknown.

I was able to track it down to the function `extractFederationServiceSDL` in the file https://github.com/kamilkisiela/graphql-hive/blob/main/packages/libraries/client/src/internal/reporting.ts. It looks like `_entities` is missing from the `federationV2.queryFields` Set. Manually adding `_entities` to the Set in my `node_modules` folder resolved the issue for me.

Please let me know if you have any questions or need any other info.

Thanks for the work you are doing!

**Comment by kamilkisiela** [comment]
Thank you for reporting this, I fixed it in #1357
