### ISSUE TITLE
We try to use with our own gateway. It should be /sdl instead of /supergraph, otherwise we'll get 404. 

### ISSUE THREAD

**Issue by hienqn** [kamilkisiela/graphql-hive#1370]
https://github.com/kamilkisiela/graphql-hive/blob/9aff954c118618e89d7a1ba13c89a98ead7c87b4/packages/libraries/client/src/apollo.ts#L47

**Comment by dotansimha** [comment]
Hi @hienqn , what kind of project did you create? was is Federation or Single?

**Comment by hienqn** [comment]
It's federation! I followed the steps outlined here https://github.com/kamilkisiela/graphql-hive/blob/8287a5125557ec2c2ce17f94107b188d546fca3d/packages/libraries/client/README.md#using-the-registry-with-apollo-gateway

**Comment by hienqn** [comment]
I think the API is exposed via /sdl path but `createSupergraphManager` is using /supergraph

**Comment by dotansimha** [comment]
> It's federation! I followed the steps outlined here [`8287a51`/packages/libraries/client/README.md#using-the-registry-with-apollo-gateway](https://github.com/kamilkisiela/graphql-hive/blob/8287a5125557ec2c2ce17f94107b188d546fca3d/packages/libraries/client/README.md#using-the-registry-with-apollo-gateway)

The steps mentioned here are for consuming the Supergraph using the Apollo gateway/router. I asked what kind of Project you created on your **Hive** instance because only the Federation project type will have the `/supergraph` endpoint. So the project you create on Hive must match your actual runtime.  

@n1ru4l what do you think?

**Comment by n1ru4l** [comment]
We have an integration test that shows this is working as expected

https://github.com/kamilkisiela/graphql-hive/blob/main/integration-tests/tests/api/artifacts-cdn.spec.ts#L376
https://github.com/kamilkisiela/graphql-hive/blob/2e0106739a95455562e342a4b8d797934594902e/integration-tests/tests/api/artifacts-cdn.spec.ts#L399-L404

@hienqn Can you please double-confirm this is a federation project and that you are using the correct `HIVE_CDN_ENDPOINT `?

As @dotansimha mentioned the `/supergraph` endpoint exists only for federation projects.

**Comment by hienqn** [comment]
Hello @dotansimha and @n1ru4l, sorry for the confusion. I thought I created a federated project, but it turned out it was my mistake! Thanks for looking into this.
