### ISSUE TITLE
Unable to run Hive locally with external composition enabled

### ISSUE THREAD

**Issue by CPerry26** [kamilkisiela/graphql-hive#1469]
Hiya! Hope you're all doing well.

We currently have all of our graphs running in an Apollo Federation v2 federated graph with the Apollo Gateway. We wanted to explore moving to use the Guild tooling to achieve the same functionality. I've been exploring running Hive locally (in the future with Mesh) with external composition enabled, but unfortunately I've been running into issues publishing my schema. The error I'm receiving in the Hive logs is the following (sensitive info removed):

```
docker-server-1                | {"level":30,"time":1677171225731,"pid":1,"hostname":"4c0bcdf7e400","msg":"Publishing schema (input={\"service\":\"identity\",\"url\":\"http://localhost:3000/graphql\",\"author\":\"FAKE_AUTHOR_NAME\",\"commit\":\"COMMIT_ID\",\"experimental_acceptBreakingChanges\":false,\"github\":false,\"checksum\":\"+M2xwukQIgdNYSlfmQkAWg==\",\"isSchemaPublishMissingUrlErrorSelected\":true,\"organization\":\"b5e4d621-4165-4d58-8b2c-4a5c778eb9ab\",\"project\":\"8c8663e9-19d3-4788-9ab6-5f509bfc9dd6\",\"target\":\"4d3c47c7-b298-4158-a4ed-846e4381b8f2\",\"sdl\":4774,\"experimental_accept_breaking_changes\":false,\"metadata\":false}) - (requestId=izONjSSlQV2hS+8p8N30uQ/0000000000)"}

docker-tokens-1                | {"level":30,"time":1677171225736,"pid":1,"hostname":"011fafeb6cea","msg":"[200] (::ffff:172.31.0.17) GET /trpc/getToken?input=%7B%22token%22%3A%226eb3bed51cc002156cbde52693d8f57c%22%7D (reqId=izONjSSlQV2hS+8p8N30uQ/0000000000)"}

docker-schema-1                | {"level":50,"time":1677171226957,"pid":1,"hostname":"0e8a896aded2","reqId":"izONjSSlQV2hS+8p8N30uQ/0000000000","msg":"connect ECONNREFUSED 127.0.0.1:3069"}

docker-schema-1                | {"level":50,"time":1677171226960,"pid":1,"hostname":"0e8a896aded2","msg":"[500] (::ffff:172.31.0.17) POST /trpc/validate (reqId=izONjSSlQV2hS+8p8N30uQ/0000000000)"}

docker-server-1                | {"level":50,"time":1677171226966,"pid":1,"hostname":"4c0bcdf7e400","msg":"**connect ECONNREFUSED 127.0.0.1:3069\n\nGraphQL request:2:3\n**1 | mutation schemaPublish($input: SchemaPublishInput!, $usesGitHubApp: Boolean!) {\n2 |   schemaPublish(input: $input) {\n  |   ^\n3 |     __typename - (requestId=izONjSSlQV2hS+8p8N30uQ/0000000000)"}

docker-server-1                | {"level":50,"time":1677171226966,"pid":1,"hostname":"4c0bcdf7e400","msg":"**connect ECONNREFUSED 127.0.0.1:3069\n\nGraphQL request:2:3\n**1 | mutation schemaPublish($input: SchemaPublishInput!, $usesGitHubApp: Boolean!) {\n2 |   schemaPublish(input: $input) {\n  |   ^\n3 |     __typename - (requestId=izONjSSlQV2hS+8p8N30uQ/0000000000)"}

docker-server-1                | {"level":30,"time":1677171226968,"pid":1,"hostname":"4c0bcdf7e400","msg":"[200] (::ffff:172.31.0.1) POST /graphql 'schemaPublish'"}
```

Here is the Hive CLI command:
`npx hive schema:publish ./build/schema.graphql --service fake_service_name --url http://localhost:3000/graphql`

I can access the /_readiness endpoint in my browser and get the "Ok." response (also verified the composition service printed it's running on localhost at the expected port). The Hive instance and the external composition service are both running on localhost. I have tried different ports than 3069, as well as using the IP address directly instead of localhost in the Hive UI, both result in the same error. I followed the steps [here](https://docs.graphql-hive.com/self-hosting/get-started) and [here](https://docs.graphql-hive.com/features/external-schema-composition#apollo-federation-v2-example) for running Hive locally with the provided federation v2 external composition image. I made sure the secrets match in both the Hive UI and what I started the image with. Here are the image versions I'm using:
Hive image tag: f66f6714d5841620d8fa224b67907c534e21470b
Composition image tag: It's listed as latest (I pulled this morning), and this is my image shown in the history of the image => 256ba5312c76.

I'm likely not doing something correctly to enable Hive to talk to the external service, but I'm not sure what it is from the guides. If you need any more information please let me know and I will get it! Thanks :)

**Comment by n1ru4l** [comment]
Hey @CPerry26, great to hear that you want to explore Hive!

From looking at your logs it seems like the configuration might be wrong.

```
docker-server-1 {"level":50,"time":1677171226966,"pid":1,"hostname":"4c0bcdf7e400","msg":"**connect ECONNREFUSED 127.0.0.1:3069
```

The `server` container tries to connect to `http://127.0.0.1:3069` WITHIN the `server` docker container. Instead it should connect to the host/ip of the container.

We recommend adding the container to the `docker-compose.community.yaml` file, similar to what we are doing in the integration tests: https://github.com/kamilkisiela/graphql-hive/blob/4b095a00ed86232e9479756044b955506f073291/integration-tests/docker-compose.integration.yaml#L62-L71

Instead of using `http://127.0.0.1:3069`, you then need to use `http://composition_federation_2:3069`, as the host for the composition service, as this is the hostname exposed in the internal docker network.

You can learn more on networking in docker-compose here: https://docs.docker.com/compose/networking/
