### ISSUE TITLE
GraphQL Operations Detail Page

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#1579]
Client, samples, timings and so on.

**Comment by n1ru4l** [comment]
Currently, we only show the following when clicking on a GraphQL operation in the `Operations` tab of a target:
<img width="1336" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/cdd19ea0-dccf-4c14-8df3-ec1dbd8dc615">

We should answer the following questions

- Which clients and which client versions execute this operation
- What is the overall latency for this specific Operation (same information as in list view)
- What is the overall latency for this specific Operation (over time?)
- Failure rate over time
- Requests over time
