### ISSUE TITLE
Filter for `@deprecated` directive on Schema Explorer

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#1580]
Filter for only showing schema coordinates/fields with `@deprecated` directive on the explorer page.

This should help teams to quickly identify which deprecated things are still used by which client/team in order to inform them that they should stop using that field.

**Comment by cassidycodes** [comment]
+1 on this issue! We'd love to see this.

**Comment by kamilkisiela** [comment]
https://the-guild.dev/graphql/hive/product-updates/2024-04-09-deprecated-schema-view
