### ISSUE TITLE
Hive cli schema:publish unable to publish schemas to a federated project when --url has no protocol

### ISSUE THREAD

**Issue by alanquigley-toast** [kamilkisiela/graphql-hive#1604]
`yarn hive schema:publish ./schema.graphql --url /my-service/graphql --service my-service`

The latest hive-cli fails with the following error when publishing to a Federated project. This worked previously for me.

✖ Missing service url Please use the '--url <url>' parameter.
 
 It works if we switch the `--url` to include a protocol.
 
 `yarn hive schema:publish ./schema.graphql --url https://my-service/graphql --service my-service`
 
 When a build service function is implemented in the gateway, publishing without a protocol is helpful, as this can be set later via an environmental variable. 

 Thank! and please reach out if I can assist in anyway.

**Comment by dotansimha** [comment]
Hi @alanquigley-toast 

We've recently [fixed a bug](https://github.com/kamilkisiela/graphql-hive/issues/330) with the schema validation checks, and introduced a validation for the URL. So now the published URL from the Hive CLI must be a fully valid URL. 

The URL published must be valid because otherwise it will results in a broken Supergraph for Apollo Gateway.

**Comment by alanquigley-toast** [comment]
That makes sense; we implemented our solution https://www.apollographql.com/docs/apollo-server/using-federation/api/apollo-gateway/#the-buildservice-function. Where we build the URL based on the ENV variables. But supporting a more rigid URL pattern is an easy refactor.

**Comment by Parables** [comment]
@alanquigley-toast has your issue been addressed and fixed by @dotansimha 's response?

If so, please close this issue as fixed.

If you do have any other issues, don't hesitate to create a new issue.
Thanks for trying out GraphQL Hive
