### ISSUE TITLE
Remove `graphql-request` from Hive CLI

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#1703]
It's not really in heavy use, and can be replaced with a simple `fetch` call.

**Comment by ashutosh887** [comment]
Is it resolved @dotansimha @B2o5T 
I would like to work on this if not

**Comment by B2o5T** [comment]
@ashutosh887 it was not yet resolved, see my initial attempt in linked PR

**Comment by n1ru4l** [comment]
We can use the client preset with fetch + `executeOperation` (https://github.com/dotansimha/graphql-code-generator/blob/2139f1db5704aa34a0cd89342736bf67ec556da3/examples/yoga-tests/src/yoga.spec.ts#L6-L23)
