### ISSUE TITLE
Failed to build Graphql schema on Hive

### ISSUE THREAD

**Issue by pierrebiver** [kamilkisiela/graphql-hive#1796]
Hello,

I'm using `graphql-codegen` to generate my schema. Then upload the generated schema to my self hosted graphql-hive but I think there is a bug in the schema validation/merge.

I use Federation V2 and there is an example of the declared directive in my generated schema:
```
directive @federation__composeDirective(name: String) on SCHEMA

directive @federation__extends on INTERFACE | OBJECT

directive @federation__external(reason: String) on FIELD_DEFINITION | OBJECT

directive @federation__inaccessible on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

directive @federation__override(from: String!) on FIELD_DEFINITION

directive @federation__provides(fields: federation__FieldSet!) on FIELD_DEFINITION

directive @federation__requires(fields: federation__FieldSet!) on FIELD_DEFINITION

directive @federation__tag(name: String!) on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

directive @key(fields: federation__FieldSet!, resolvable: Boolean = true) on INTERFACE | OBJECT

directive @link(as: String, for: link__Purpose, import: [link__Import], url: String) on SCHEMA

directive @shareable on FIELD_DEFINITION | OBJECT
```

Because I extend `@key` in my schema, it generates the directive without the `federation` namespace but the field type is `federation__FieldSet`. When I try to upload my schema to my self hosted Hive I get the following error:
`Invalid definition for directive "@key": argument "fields" should have type "_FieldSet!" but found type "federation__FieldSet!"`. Is this a bug or something that I did not configured properly ?

**Comment by dotansimha** [comment]
Hi @pierrebiver 
Are you using [External Schema Composition](https://docs.graphql-hive.com/management/external-schema-composition) in your project? Because that's the only way to run Federation v2 at the moment (see the notes on the page I linked).

**Comment by pierrebiver** [comment]
Looking at your code, it seems to be an error with Apollo as they do the validation. I'll close this issue then.
