### ISSUE TITLE
✖ Failed to publish schema

### ISSUE THREAD

**Issue by vijayakumarit** [kamilkisiela/graphql-hive#187]
Hi @charlypoly 

I am facing an error while publishing the schema. I have followed all the steps and then I have generated the token as well. Finally, I am running the command "hive schema: publish".mesh/schema.graphql". Basically, I have already completed the GraphQL Mesh. Now I tried "Hive" for the CI/CD pipeline. I am facing the below error. Just update me if I am doing anything wrong.

Error:

vijayakumar@Vijayakumars-MacBook-Pro postgres-geodb % hive schema:publish ".mesh/schema.graphql" --force
(node:35108) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✖ Failed to publish schema
 ›   Error: Unexpected error.
 ›   Reference: 6e4f3f1e-b58c-419c-9580-72c10be689fa

**Comment by kamilkisiela** [comment]
It looks like your token is incorrect, it has 31 characters and should have 32. 
You should see an error saying "Invalid token" but it's lost during error masking (#188).

**Comment by vijayakumarit** [comment]
@kamilkisiela , Thanks buddy. I fixed the token now. I was a bit confused by the error.
