### ISSUE TITLE
error masking should always be enabled

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#189]
Currently, error masking is only enabled in `staging` and `production` environments. It should also be enabled in development mode, so the behavior is as close as possible.

**Comment by kamilkisiela** [comment]
yes

**Comment by saihaj** [comment]
But in `dev` you also want to be able to look at stack traces to help debugging?

**Comment by n1ru4l** [comment]
@saihaj Please read the yoga docs 😁 https://www.graphql-yoga.com/docs/features/error-masking#receive-original-error-in-development
