### ISSUE TITLE
(self hosted) graphql-hive no longer compatible with google cloud storage

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#2151]
**Context:**
- we're using Hive self-hosted 
- Due to company limitations we cant use S3/Cloudflare as CDN
- Since the s3 sdk is compatible with Google Cloud  Storage (GCS) we configured Hive to connect with our GCS instance instead
- This worked fine until we tried to update to a newer version

The last version (that we tested) which worked is: 72b036a3083ef437c0269c4359c856291d262de6 (20-12-2022)

After upgrading to version fb63517c7e78528645c5e87411b75513e85ccb99 (23-03-2023) our self hosted setup broke.

**Assumptions below**
I quickly browsed through the changes and saw that the native s3 client was replaced with aws4fetch between these above mentioned versions. Perhaps this is the cause of the error?

**Logging**
Below is the logging i found in the container after trying to push a new schema to Hive

> {"context":{"connectionId":"pO-Xo2fAQIaY0kJ3EK1A3A-271","error":{"message":"Unexpected status code 400 when writing artifact.","name":"Error","stack":"Error: Unexpected status code 400 when writing artifact.    at ArtifactStorageWriter.writeArtifact (file:///usr/src/app/index.js:213541:13)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.all (index 1)
>     at async publishCompositeSchema (file:///usr/src/app/index.js:214304:7)
>     at async Promise.all (index 0)
>     at async SchemaPublisher2.updateCDN (file:///usr/src/app/index.js:214371:5)
>     at async SchemaPublisher2.publishToCDN (file:///usr/src/app/index.js:214271:5)
>     at async Object.actionFn (file:///usr/src/app/index.js:214158:11)
>     at async file:///usr/src/app/index.js:221749:9
>     at async execTransaction (file:///usr/src/app/index.js:158431:24)
>     at async transaction (file:///usr/src/app/index.js:158485:16)
>     at async createConnection (file:///usr/src/app/index.js:159048:18)
>     at async Object.transaction (file:///usr/src/app/index.js:158737:18)
>     at async Object.createVersion (file:///usr/src/app/index.js:221694:22)
>     at async SchemaPublisher2.internalPublish (file:///usr/src/app/index.js:214142:27)
>     at async executor (file:///usr/src/app/index.js:213803:18)"},"logLevel":50,"package":"slonik","poolId":"pO-Xo2fAQIaY0kJ3EK1A3A-0","transactionId":"pO-Xo2fAQIaY0kJ3EK1A3A-272"},"message":"rolling back transaction due to an error","sequence":"569","time":1679655763251,"version":"2.0.0"}

**Comment by kamilkisiela** [comment]
Hi @rickbijkerk since we're not using GCS, only R2 and S3, we can't promise Hive will always be compatible with GCS, but we're open to introduce a feature flag that enables to switch between two S3 client implementations (our own and AWS S3).

We will be happy to accept a Pull Request implementing that. Are you interested in submitting one?

**Comment by kamilkisiela** [comment]
The reason was incompatibility with Cloudflare Workers if I remember correctly (@n1ru4l?)

**Comment by n1ru4l** [comment]
@kamilkisiela Yeah, the official AWS S3 SDK does not run on Cloudflare Workers and AWS does not plan to support that environment.

However, given [the latest announcement](https://blog.cloudflare.com/workers-node-js-asynclocalstorage/), we could try using the S3 SDK again.

______

Aside from that, the `ArtifactStorageWriter` class actually does not need to run on Cloudflare Worker and could use the official [`aws-sdk-js-v3`](https://github.com/aws/aws-sdk-js-v3).

**Comment by n1ru4l** [comment]
Same seems to happen with native S3: https://github.com/kamilkisiela/graphql-hive/issues/2230#issuecomment-1546188143

**Comment by kamilkisiela** [comment]
If anyone wants to help us implement what @n1ru4l wrote, feel free.

**Comment by ashutosh887** [comment]
Please let me work on this @rickbijkerk @n1ru4l @kamilkisiela

**Comment by B2o5T** [comment]
@ashutosh887
as @kamilkisiela said https://github.com/kamilkisiela/graphql-hive/issues/2151#issuecomment-1554239898 if somebody want to work on it feel free, any help is appreciated
