### ISSUE TITLE
Cannot find module 'apollo-server-plugin-base' or its corresponding type declarations

### ISSUE THREAD

**Issue by robertherber** [kamilkisiela/graphql-hive#219]
I'm using this library with `graphql-yoga` and `fastify` and I end up with having to install `apollo-server-plugin-base` because I'm getting this type error:
```node_modules/@graphql-hive/client/apollo.d.ts:1:41 - error TS2307: Cannot find module 'apollo-server-plugin-base' or its corresponding type declarations.

import type { ApolloServerPlugin } from 'apollo-server-plugin-base';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@graphql-hive/client/apollo.d.ts```

**Comment by davidruisinger** [comment]
Intermediate fix:

Create a `missing_apollo_types.d.ts` file in your project with the following content:
```
declare module 'apollo-server-plugin-base' {
  interface ApolloServerPlugin {
    _: unknown
  }
}
```

**Comment by dotansimha** [comment]
@ardatan @enisdenjo @kamilkisiela can we use Bob to create a different entry point for the `apollo.ts` file? 
This way it will not get loaded by TS by default? 
It seems like the export in https://github.com/kamilkisiela/graphql-hive/blob/main/packages/libraries/client/src/index.ts#L3 requires users to have that package as a dependency, or it fails compilation? 

(I know `skipLibCheck` is also an option here, but I wasn't sure if that's the recommendation for such case?)

**Comment by enisdenjo** [comment]
Hmm, am not fully sure but cant we just not export apollo from index? So that apollo needs to be imported directly.

**Comment by ardatan** [comment]
@dotansimha I think a seperate package is the best option here

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/issues/4571

**Comment by kamilkisiela** [comment]
https://the-guild.dev/graphql/hive/product-updates/2024-04-23-graphql-server-integrations-workers-support
