### ISSUE TITLE
hive publish command stops working after a while, server container restart resolves it

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#2209]
Hey, we're seeing a weird issue on our side. 

It seems that after a certain amount of time/usage (unsure which) roughly a day our hive-registry is unable to handle publishes of schemas.

For the publishing of the schema we use the hive CLI `hive schema:publish ..`

The error we see in the logs is:

> {"context":{"package":"slonik","poolId":"BxFDAve7R2uvQh9QmFfECg-0","connectionId":"BxFDAve7R2uvQh9QmFfECg-1030","queryId":"BxFDAve7R2uvQh9QmFfECg-4830","logLevel":20,"sql":"select pg_try_advisory_lock($1) as advisoryLock","values":[899406362]},"message":"executing query","sequence":"7695","time":1683630102225,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"BxFDAve7R2uvQh9QmFfECg-0","connectionId":"BxFDAve7R2uvQh9QmFfECg-1030","queryId":"BxFDAve7R2uvQh9QmFfECg-4830","logLevel":50,"error":{"name":"Error","message":"Client has encountered a connection error and is not queryable","stack":"Error: Client has encountered a connection error and is not queryable\n    at file:///usr/src/app/index.js:164997:32\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"}},"message":"execution routine produced an error","sequence":"7696","time":1683630102225,"version":"2.0.0"}
{"context":{"package":"slonik","poolId":"BxFDAve7R2uvQh9QmFfECg-0","connectionId":"BxFDAve7R2uvQh9QmFfECg-1030","queryId":"BxFDAve7R2uvQh9QmFfECg-4830","logLevel":50,"error":{"notices":[],"name":"Error","message":"Client has encountered a connection error and is not queryable","stack":"Error: Client has encountered a connection error and is not queryable\n    at file:///usr/src/app/index.js:164997:32\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"}},"message":"query execution produced an error","sequence":"7697","time":1683630102225,"version":"2.0.0"}
{"level":50,"time":1683630102228,"pid":13,"hostname":"hive-server-deployment-75c5bc7658-l9wmp","msg":"Client has encountered a connection error and is not queryable\n\nGraphQL request:2:3\n1 | mutation schemaPublish($input: SchemaPublishInput!, $usesGitHubApp: Boolean!) {\n2 |   schemaPublish(input: $input) {\n  |   ^\n3 |     __typename - (requestId=f39ef34e-7ea7-4d33-8701-3a5163da403f)"}
{"level":30,"time":1683630102228,"pid":13,"hostname":"hive-server-deployment-75c5bc7658-l9wmp","msg":"[200] (127.0.0.6) POST /graphql 'schemaPublish' (reqId=f39ef34e-7ea7-4d33-8701-3a5163da403f)"}

This is what it looks like from the 'hive publish' command side
![image](https://github.com/kamilkisiela/graphql-hive/assets/2291474/44fee607-8bef-41e2-88ed-9d920414dc4b)

The weird thing is that hive schema:check and other frontend calls keep on working.

### Notes
- we're using version 72b036a (20-12-2022) of the hive-registry
- Unfortunately updating to a newest version to rule out any bugs that are already fixed is blocked by : https://github.com/kamilkisiela/graphql-hive/issues/2151 

### Theories
- The publish command uses a different database connection pool and is not able to properly handle all sorts of errors that can happen between a db and an application (e.g. network reset)

### How we can 'fix' it
By specifically restart the 'server image' (as in not the entire stack) it resolves the issue.

Would love to hear if this rings a bell, or if you have any ideas what it might be!
If you need any more info let me know!

p.s. is there a way to enable more logging within hive, perhaps some environment variable?

**Comment by kamilkisiela** [comment]
There could be a connection issue on Postgres side that made Slonik (pg client) stuck. I think it's solved in the newer versions of GraphQL Hive.


I'm closing this one as it's already fixed. The only blocker for you to upgrade is [Google Cloud Storage support](https://github.com/kamilkisiela/graphql-hive/issues/2151), but we already described what could be done there.
