### ISSUE TITLE
`hive schema:check` fails in latest version

### ISSUE THREAD

**Issue by nils-jansen** [kamilkisiela/graphql-hive#2269]
Running `hive schema:check` with CLI version 0.21.0 works as expected.

After updating to version 0.22.0, I get the following error:
```
✖ Failed to check schema
 ›   Error: Cannot query field "warnings" on type "SchemaCheckSuccess".
 ›   Reference: <reference>
```
The error seems to be raised [here](https://github.com/kamilkisiela/graphql-hive/blob/f55998a619c688a6d4c3cf210d110f323e00fb2d/packages/libraries/cli/src/commands/schema/check.ts#L165).

I have been using the CLI inside a GitHub Action which has now stopped working correctly - it would be great if I could pin the CLI version by passing the desired version to the install script. What do you think about this idea?

**Comment by n1ru4l** [comment]
Hey @nils-jansen, are you self-hosting? In that case please make sure you upgraded your Hive instance to the latest version.

**Comment by nils-jansen** [comment]
Hi @n1ru4l - yes I am, will do that now, thanks :)
