### ISSUE TITLE
GraphQL Hive Client for workers

### ISSUE THREAD

**Issue by ilijaNL** [kamilkisiela/graphql-hive#2492]
Looking at the current code of @graphql-hive/client, it seems that the client won't work inside an edge (cf) worker? Am I correct, and if so, is it on the roadmap?

The use-case is to use vercel/cf workers for usage reporting.

**Comment by kamilkisiela** [comment]
It would require some adjustments (dispose the client with `context.waitUntil`) but in a matter of a few lines of code you could make it work. Here's [the core logic](https://github.com/kamilkisiela/graphql-hive/blob/ae98aa978536f7df541db7a975b877e3814d3cfe/packages/libraries/client/src/client.ts#L10) that you could use (both envelop and apollo plugins are using it under the hood).

**Comment by ilijaNL** [comment]
I see, my concern was more about using axios as an agent client instead of whatwg fetch for example

**Comment by ilijaNL** [comment]
> I see, yeah it needs to be replaced by something platform agnostic like Fetch API.
> 
> Instead of envelop, you could use our (of [The Guild](https://the-guild.dev/)) [GraphQL Yoga](https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-cloudflare-workers).

I don't think this will fix using hive client in workers env since under the hood it still uses the @graphql-hive/client package. 

Anyways I will try to write my own agnostic hive client for the time being

**Comment by kamilkisiela** [comment]
> I see, yeah it needs to be replaced by something platform agnostic like Fetch API.

But that's what I meant, to replace axios with something like Fetch API.

**Comment by ilijaNL** [comment]
I created simple edge client (only usage reporting for now) here: https://www.npmjs.com/package/graphql-hive-edge-client

My use case is to use edge functions as a (security) proxy which does analytics with graphql hive

**Comment by kamilkisiela** [comment]
CF Worker support coming soon #4494

**Comment by kamilkisiela** [comment]
https://the-guild.dev/graphql/hive/product-updates/2024-04-23-graphql-server-integrations-workers-support
