### ISSUE TITLE
Optimize schema check storage of composite sdl and supergraph

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#2603]
Right now we store the composite SDL and supergraph on every record within the `schema_checks` table.

When a schema check runs that has no active changes within the schema, we store a lot of redundant data within our database. E.g. bots like renovate cause a lot of these runs. Some GraphQL schemas are quite huge.

A lot of `schema_checks` are linked to the `schema_versions` table, which also stores the composite SDL and supergraph.
In case a schema check has no active changes (read as the same checksum), we could omit to store the composite SDL and supergraph within the `schema_checks` table and instead retrieve them from the `schema_versions` table when consuming the field via the GraphQL API.

A further optimization could be to even store schemas and their checksums in a completely new table, e.g. `checksum_schemas`, that is a `checksum` to `SDL` mapping. That way we could furthermore reduce the redundancy of large SDL strings.

**Note:** If we do the latter, we also need to make sure the cleanup happens when the checksum entry is no longer referenced by any `schema_checks` entry, which would furthermore complicate the database schema.

**Comment by andriihrachov** [comment]
would like to take it

**Comment by n1ru4l** [comment]
Hey @andriihrachov, feel free to send a pull request! I would be happy to review it ☺️

**Comment by kamilkisiela** [comment]
@andriihrachov before touching code, do you mind sharing with us when do you plan to work on it and how you want to implement it?

**Comment by andriihrachov** [comment]
@kamilkisiela sorry I missed your message, but opened a PR with first steps (migration, recording schema SDL and checksum in separate table, etc,) - it's quite small to kill if I took wrong way, pls feedback :)
