### ISSUE TITLE
The running SuperTokens core version is not compatible with this NodeJS SDK

### ISSUE THREAD

**Issue by pierrebiver** [kamilkisiela/graphql-hive#2670]
Hello,

We use a self-hosted version of Hive and I tried to update to the latest docker tag but I'm getting the following error:
```
The running SuperTokens core version is not compatible with this NodeJS SDK. Please visit https://supertokens.io/docs/community/compatibility to find the right versions
    at Querier.<anonymous> (/usr/src/app/node_modules/.pnpm/supertokens-node@14.1.3/node_modules/supertokens-node/lib/build/querier.js:133:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/.pnpm/supertokens-node@14.1.3/node_modules/supertokens-node/lib/build/querier.js:51:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I can see there is a pinned issue due to a migration to Supertoken 5 but I'm not sure it's related.

**Comment by n1ru4l** [comment]
Hey @pierrebiver!

Please double-check check you are running the correct docker image versions. If you just updated the docker-compose file and run docker compose up it is very likely that you are still running the old images. The --force-recreate flag can be used for recreating the containers.

See [docs.docker.com/engine/reference/commandline/compose_up](https://docs.docker.com/engine/reference/commandline/compose_up)

**Comment by pierrebiver** [comment]
Hello, 
I followed the migrations by the letter.  And I always use `force-recreate` flag when updating but I still get the error regarding the node js version.

**Comment by n1ru4l** [comment]
Can you please share the git commit sha that you are using?

**Comment by pierrebiver** [comment]
Sure,
After running the migration I used this docker tag: `a90f25b953487c3b13bca8eaff1722ae7038f52f`
I even tried with the latest one: `ee8fc94b006601d9a5690be703d29c1f5c4f1358` but I'm getting the same error.

**Comment by n1ru4l** [comment]
It seems like you might be using the wrong SuperTokens version.

**Comment by pierrebiver** [comment]
ahh in the docker file it says 4.4... my bad I'm sorry I thought the docker tag would take care of that

**Comment by n1ru4l** [comment]
@pierrebiver The docker-compose file states the correct version here:
https://github.com/kamilkisiela/graphql-hive/blob/77b922c479d8dc306876e22c4b7fb4f08e329d5a/docker/docker-compose.community.yml#L114-L115
