### ISSUE TITLE
GraphQL Hive CLI does not support linux / aarch64 at this time.

### ISSUE THREAD

**Issue by ocdrums3** [kamilkisiela/graphql-hive#2683]
I'm following [the docs](https://the-guild.dev/graphql/hive/docs/integrations/ci-cd#github-workflow-for-ci) to install the hive CLI in ubuntu, and when running the provided command `curl -sSL https://graphql-hive.com/install.sh | sh` I get the error:

`GraphQL Hive CLI does not support linux / aarch64 at this time.`

Any suggestions?

**Comment by kamilkisiela** [comment]
I believe #3445 fixes it

**Comment by jpboily-axceta** [comment]
Actually, it does not work because the scripts downloads the arm 32bits package. On aarch64, it should download the arm64 package. I tried it manually and it worked as when I simply used the script, I got an error saying:

```
2.487 qemu-arm: Could not open '/lib/ld-linux-armhf.so.3': No such file or directory
```
