### ISSUE TITLE
Laboratory Mocking now broken

### ISSUE THREAD

**Issue by danielmcconville** [kamilkisiela/graphql-hive#2686]
Hi,

PR #2680 seems to have broken the original mocking functionality of the Laboratory. We were using the Laboratory to return mock data for our schema and it was working fine, but now it says `no endpoint linked` and a button to connect the endpoint:

![image](https://github.com/kamilkisiela/graphql-hive/assets/22184784/3c5183dc-9e22-46f5-b3ef-c984d96cb14e)

I am assuming that this wasn't an intentional change? #788 seemed to want to add the ability to connect hive to a real server rather than replace it. Or am I missing a configuration option somewhere that delivers the original mocking functionality?

Thanks.

**Comment by kamilkisiela** [comment]
We removed it as we've seen very minimal usage of that feature and from what we knew, people were using it mostly for introspection queries (and we advised them to use our CDN).
We will bring that feature back if it's really needed. 

Can you describe a bit your use-case? Usually mocking can be done in a way where you fetch the schema from Hive's CDN but you mock the data on your own using https://the-guild.dev/graphql/tools/docs/mocking. This way you control how to mock and what.

**Comment by danielmcconville** [comment]
Ah, OK. That sounds reasonable. We were using it as a bridge between two companies that are working together on schema first development. It has been useful in the initial stages before we have a mock server up and running as we have been able to commence working out the schema design with minimal setup. We will deploy a mock server soon so at that point the feature will not be needed but up till now it has been useful to us.

**Comment by n1ru4l** [comment]
@danielmcconville We decided to bring back that feature. Sorry for the inconvenience. I will ping you again once we shipped it.

**Comment by danielmcconville** [comment]
@n1ru4l OK, great - thanks!

**Comment by n1ru4l** [comment]
@danielmcconville It is again on the main branch and deployed to production.

**Comment by danielmcconville** [comment]
@n1ru4l great, thank you very much!!
