### ISSUE TITLE
Feature Request: Search operations and link types/fields to operations

### ISSUE THREAD

**Issue by yogeshdengle** [kamilkisiela/graphql-hive#2704]
Current state:
Currently I can search for Types under explorer and it gives me the fields of that type and their usage stats and the user details if any.

Requested Feature:
Allow the user to click through from the usage stats to the actual queries that use that Type/field.

Current State:
In the Operations tab I cannot search for queries

Request Feature:
Allow user to search by query name, query contents etc.

These features will help enormously in finding schema usages.
Thank you!

**Comment by kamilkisiela** [comment]
We're going to implement these two views:
- https://github.com/kamilkisiela/graphql-hive/issues/2443
- https://github.com/kamilkisiela/graphql-hive/issues/1579

This way we could link types/fields <-> operations <-> clients as each will have its own dedicated view.

Do you think we could close this issue or the two above are not related to your feature request?

**Comment by yogeshdengle** [comment]
Appreciate the quick revert, The first ask gets solved by https://github.com/kamilkisiela/graphql-hive/issues/2443 , but the second is not covered by either.

**Comment by n1ru4l** [comment]
It is possible to search for operations:

![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/5ba95d01-1769-44d8-a560-beb055a8e30b)


It is also possible to see the top operations that use a field in the GraphQL schema.
![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/640428d5-ecc5-4fe9-83b8-4c075afd20a5)

Please in the future open dedicated issues for each feature request so it is easier to keep track!
