### ISSUE TITLE
GraphQL Schema versioning access

### ISSUE THREAD

**Issue by voslartomas** [kamilkisiela/graphql-hive#2716]
Hello,

we would like to have possibility to download schema from the past, this is mainly need of our clients which are developing chrome plugins and in case of bug, they need build older version (with older schema), nowadays our pipelines are able to fetch only latest SDL from CDN.

**Comment by n1ru4l** [comment]
Do you need the previous schema versions to be downloaded from the CDN, or would it be fine if those were fetched from the GraphQL API instead? We already store the previous schema versions within the PG SQL database, so it would be easy to make these downloadable via the CLI.

Another question is what unique identifier you want to use for downloading these schemas. Each schema version has it's own unique UUID (e.g. `bb0ad5af-95ed-4dd7-9afd-78bc47988a2a`). However, I am pretty sure you would rather fetch a version via its SHA hash. Is that correct?

From a technical position, it is possible that multiple schema versions within a single target share the same (git) SHA hash, thus making it impossible to uniquely identify a schema version by that.

A workaround we could do is to always return the first hash that comes up.

**Comment by voslartomas** [comment]
It would be nice to have it behind CDN, but for start it will be for sure enough to have it at least from API.

Commit hash seems like best approach to get schema for specific version.

I think we don't mind that versions will have same git sha hash as long as we are able to get single schema for this hash, so as you wrote first or maybe latest version for this hash should be fine.
