### ISSUE TITLE
Light theme in Hive UI

### ISSUE THREAD

**Issue by voslartomas** [kamilkisiela/graphql-hive#2719]
It would be nice to have light theme, if not in whole UI at least inside Laboratory, where developers spend most of their time.

**Comment by n1ru4l** [comment]
https://github.com/graphql/graphiql/issues/3398

**Comment by n1ru4l** [comment]
We currently, do not plan to add a light mode.

**Comment by boonstra-acorns** [comment]
I actually have visual issues which make your implementation of a dark theme (essentially fully white on fully black) painful to read. Could you reconsider? My work is moving to use your software and I don't know how I'm going to actually use it in this state.

**Comment by boonstra-acorns** [comment]
Did you merge the light theme request with the ticket that undoes any chance of implementing a light theme or am I misreading? Does 2819 work towards enabling theme support or is this just evidence that light theme won't be implemented?
