### ISSUE TITLE
Hive CLI schema:publish no longer mentions what changes were made

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#2732]
We're using:
- hive cli version: 0.23.0 
- Hive-registry from 27-06 (is there a way to find my hive-registry version somewhere in the application itself)
- We migrated our project in Hive to the new 'schema publish flow' (the popup thing on the bottom right)

When we do a schema:check we see all changes that are about to be made. 
When we perform the schema:publish it only says "schema published" However if my memory serves me right it did show a list of changes in the past.

expected behaviour: see a list of changes the schema:publish command did

I tried updating the hive-cli to a newer version but ran into an issue; something with webUrl if i remember correctly.
Is this somehow a mismatch between the hive cli and the hive registry? Is there a compatibility matrix somewhere?

**Comment by rickbijkerk** [comment]
now that i've given it. some more thought; i can ofcourse run a schema:check before the schema:publish in the same gitlab job to get the same result.

I think my main question is; is this intended or is this caused by us not using the latest version of hive/cli?

**Comment by n1ru4l** [comment]
When publishing a schema we no longer check for breaking changes. You can see all the changes of a schema version on the Hive App. If you want to check for breaking changes before publishing you can use `hive schema:check`.
