### ISSUE TITLE
CDN not working with AWS S3

### ISSUE THREAD

**Issue by adiii717** [kamilkisiela/graphql-hive#2736]
The configuration operates smoothly with MinIO and Caddy; however, it encounters issues when attempting to utilize AWS S3
server image `ghcr.io/kamilkisiela/graphql-hive/server:7399aa50bef74464c0012c360479a1a927d7a1a0`

Here are the environment variables
```
  "S3_ACCESS_KEY_ID": "xxxx",
  "S3_BUCKET_NAME": "my-bucket",
  "S3_ENDPOINT": "https://s3.us-west-2.amazonaws.com",
  "S3_PUBLIC_URL": "https://caddy.example.com",
  "S3_SECRET_ACCESS_KEY": "xxxx",
```
and caddy
```
      - command:
        - caddy
        - reverse-proxy
        - --from
        - :8083
        - --to
        - my-bucket.s3-us-west-2.amazonaws.com:443
        - --change-host-header
 ```
also tried to enable debug logs and specify AWS keys but no luck

```
        env:
        - name: CADDY_LOG
          value: debug
        - name: AWS_ACCESS_KEY_ID
          value: xxx
        - name: AWS_SECRET_ACCESS_KEY
          value: xx/xx/xx
```
<img width="664" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/23054298/07002634-b7a8-4597-83bb-3f70d5a3d39a">

<img width="664" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/23054298/b3302aaf-3e5c-4527-8d0c-0be0c8f5a730">

```
{"level":20,"time":1692161494464,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Parsing request to extract GraphQL parameters - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":20,"time":1692161494464,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Processing GraphQL Parameters - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":20,"time":1692161494483,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Translating Organization Clean ID (selector={\"organization\":\"example\"}) - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":20,"time":1692161494484,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Translating Project Clean ID (selector={\"organization\":\"example\",\"project\":\"test\"}) - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":20,"time":1692161494484,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Translating Target Clean ID (selector={\"organization\":\"example\",\"project\":\"test\",\"target\":\"development\"}) - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":20,"time":1692161494628,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"Processing GraphQL Parameters done. - (requestId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
{"level":30,"time":1692161494628,"pid":1,"hostname":"main-graphql-hive-server-dfb6d8c88-868wl","msg":"[200] (::ffff:20.1.42.167) POST /graphql 'CDNAccessTokens_CDNAccessTokenCreateMutation' (reqId=C09ip5n3Q9yOrErJz4BzJA/0000000041)"}
```

The above logs are from the server. Is there anything else I might be overlooking? Thank you.

**Comment by adiii717** [comment]
Hello @n1ru4l , could you kindly review this issue?"

**Comment by n1ru4l** [comment]
It seems like there is an error happening on either caddy or s3 that is swallowed within the business log. 

Could you add logging here and build + run the images again to gather more insight? https://github.com/kamilkisiela/graphql-hive/blob/1454ea351384e5d8c531627f8103de857485455a/packages/services/api/src/modules/cdn/providers/cdn.provider.ts#L149

**Comment by adiii717** [comment]
It indicates a 403 error from S3, even though I can successfully publish artefacts to S3, which means the server has the capability to write to S3. This situation might be related to Caddy?

```
  options: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      'x-amz-request-id': 'xxx',
      'x-amz-id-2': 'GWRLzk35qJXD1GQy3+xxxx+xx/eR40Qe5w=',
      'content-type': 'application/xml',
      date: 'Sun, 20 Aug 2023 15:26:23 GMT',
      server: 'AmazonS3',
      connection: 'close'
    },
    url: 'https://s3.us-west-2.amazonaws.com/my-bucket/cdn-keys/5f84bfb4-b3f5-4f2c-97e2-2fa777956e35/0005b7d2-9f3c-4cf8-96ec-c3e061b656c9'
  },
  bodyUsed: false,
  contentType: 'application/xml',
  contentLength: null,
  _bodyFactory: [Function: bodyFactory],
  _generatedBody: null,
  bodyType: 'Readable',
  headers: Headers {
    'x-amz-request-id': 'xxx',
    'x-amz-id-2': 'GWRLzk35qJXD1GQy3+xxxx+xx/eR40Qe5w=',
    'content-type': 'application/xml',
    date: [ 'Sun', '20 Aug 2023 15:26:23 GMT' ],
    server: 'AmazonS3',
    connection: 'close'
  },
  status: 403,
  statusText: 'Forbidden',
  url: 'https://s3.us-west-2.amazonaws.com/my-bucket/cdn-keys/5f84bfb4-b3f5-4f2c-97e2-2fa777956e35/0005b7d2-9f3c-4cf8-96ec-c3e061b656c9',
  redirected: false,
  type: 'default'
}
```

**Comment by n1ru4l** [comment]
@adiii717 Can you confirm this issue is still present without using caddy as a proxy?

**Comment by adiii717** [comment]
Hello, we've attempted various approaches to address the problem, but unfortunately, we haven't been able to find a solution. As a result, we've chosen to explore [Wundergraph](https://wundergraph.com/cosmo). Given this, we can close this issue, as I won't be able to attempt further troubleshooting personally

**Comment by n1ru4l** [comment]
Hey @adiii717, if possible please share the approaches you tried for solving your issue, so other people experiencing the same problem don't have to start from scratch.

If anyone else is reading this I am happy to re-open this issue and help finding a solution.

From the clients we work with that use S3, we recommend skippinh the caddy proxy and point to the S3 bucket directly. The caddy proxy in the docker-compose file is only there to work around local host issues with pre-signed urls.
