### ISSUE TITLE
Show a list of affected operations grouped by target in schema:check

### ISSUE THREAD

**Issue by voslartomas** [kamilkisiela/graphql-hive#2738]
Hello, another feedback when schema check fails (trying to remove field) it does not say for which target (as for most of them it shows 0 usage), it would be nice to say which target exactly has still usage so we don’t need to go one by one. Another thing around this is that if I go to specific target’s explorer page and trying to switch to another target after I am done, it will reset me to the targets main page, I would expect to stay at the same page and ideally with the same filter…

**Comment by kamilkisiela** [comment]
#2442
