### ISSUE TITLE
disable option to change the theme in laboratory and enforce the dark theme

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#2745]
We currently only have a dark theme, thus it is weird that you can choose a light theme in the GraphiQL explorer.
So we need a way to disable switching the theme and enforcing the dark theme. This should be solved in the upstream GraphiQL repository: https://github.com/graphql/graphiql/issues/3398

**Comment by kamilkisiela** [comment]
#2819
