### ISSUE TITLE
Wasted space on high resolution monitors

### ISSUE THREAD

**Issue by Troplo** [kamilkisiela/graphql-hive#2753]
This is more of a feature request per-se, but I've noticed that on my 4K monitor that the UI is very small which makes it quite annoying to use, I know 1080p is far more common and it does look great there, but I'd like if at least the web GraphQL editor/IDE took up more screen space in the future as it's quite impractical right now for development purposes.

GraphQL Hive:
![GraphQL Hive](https://i.troplo.com/i/76a34764c663.png)

Apollo Studio for comparison:
![Apollo Studio](https://i.troplo.com/i/5a1dee7375ac.png)

**Comment by n1ru4l** [comment]
Closed via https://github.com/kamilkisiela/graphql-hive/pull/3239
