### ISSUE TITLE
invalid type in docker compose

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [kamilkisiela/graphql-hive#2811]
❯ docker-compose -f docker-compose.community.yml pull
```
ERROR: The Compose file './docker-compose.community.yml' is invalid because:
services.tokens.depends_on.migrations.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.server.depends_on.migrations.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
```

**Comment by sschneider-ihre-pvs** [comment]
I think you need docker-compose 1.29.x at least

**Comment by dotansimha** [comment]
We are using the Compose specification v3.8 (https://github.com/kamilkisiela/graphql-hive/blob/main/docker/docker-compose.community.yml#L1) and this requires a Docker engine `>19.03.0+` (https://docs.docker.com/compose/compose-file/compose-versioning/)
