### ISSUE TITLE
Router container image published

### ISSUE THREAD

**Issue by rcrowe** [kamilkisiela/graphql-hive#290]
Would it be possible to build a Docker container image alongside the other binaries built during [cd](https://github.com/kamilkisiela/graphql-hive/blob/main/.github/workflows/cd.yaml) for the Apollo Router/plugin?

Perhaps this can be pushed to the Github container registry, with a tag we can pin against (latest, SHA).

If you're open to the idea & need someone else to pick it up, happy to attempt a PR.

**Comment by kamilkisiela** [comment]
Yes, definitely. If you wish to create a Pull Request I would love to merge it! :)

**Comment by rcrowe** [comment]
@kamilkisiela I've taken a stab here https://github.com/kamilkisiela/graphql-hive/pull/324 but it likely needs some setup & tweaking from yourself before it's mergeable 🙏🏻

**Comment by kamilkisiela** [comment]
#324

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/pkgs/container/graphql-hive

**Comment by rcrowe** [comment]
💥 Thanks @kamilkisiela
