### ISSUE TITLE
Running a proxy server locally?

### ISSUE THREAD

**Issue by rperryng** [kamilkisiela/graphql-hive#301]
Other GraphQL Hive integrations like [graphql-ruby-hive](https://github.com/charlypoly/graphql-ruby-hive) rely on a single endpoint proxying requests out to the different modules (`usage`, `registry`, etc), but the local development for hive doesn't include any proxy server to mimic the production environment that the gem expects.

Would adding a proxy server for local development be the right approach here since there is already code for it in the `deployment` module?  Or having client libraries support non-proxied setups?

**Comment by kamilkisiela** [comment]
I think it makes sense, the JavaScript clients have a way to configure the endpoints.

**Comment by kamilkisiela** [comment]
In local dev you can use an environment variable to point it to GraphQL API

**Comment by loteresa2** [comment]
FWIW I've been getting by with this sample code:

```typescript
const express = require('express');
const morgan = require("morgan");
const { createProxyMiddleware } = require('http-proxy-middleware');
const { json } = require('express');

// Create Express Server
const app = express();

// Configuration
const PORT = 3002;
const HOST = "localhost";
const WEB_APP_SERVICE_URL="http://localhost:3000"
const API_SERVICE_URL="http://localhost:4000"
const USAGE_SERVICE_URL="http://localhost:4001"

app.use(morgan('dev'));

app.get('/info', (req, res, next) => {
    res.send('This is a proxy service which proxies to Billing and Account APIs.');
 });

 app.use('/', createProxyMiddleware({
    target: WEB_APP_SERVICE_URL,
    followRedirects: true
}))
 app.use('/server', createProxyMiddleware({
    target: API_SERVICE_URL,
    changeOrigin: true,
    followRedirects: true,
    pathRewrite: {
        [`^/server`]: '',
    },
 }))
 .use('/registry/_health', createProxyMiddleware({
    target: API_SERVICE_URL,
    changeOrigin: true,
    followRedirects: true,
    pathRewrite: {
        [`^/registry/_health`]: '/_health',
    },
 }))
 .use('/registry', createProxyMiddleware({
    target: API_SERVICE_URL,
    changeOrigin: true,
    followRedirects: true,
    pathRewrite: {
        [`^/registry`]: '/graphql',
    },
 }))
 .use('/graphql', createProxyMiddleware({
    target: API_SERVICE_URL,
    changeOrigin: true,
    followRedirects: true,
    pathRewrite: {
        [`^/graphql`]: '/graphql',
    },
 }))
 .use('/usage', createProxyMiddleware({
    target: USAGE_SERVICE_URL,
    changeOrigin: true,
    followRedirects: true,
    pathRewrite: {
        [`^/usage`]: '',
    },
 }))

 app.listen(PORT, HOST, () => {
    console.log(`Starting Proxy at ${HOST}:${PORT}`);
 });
```

Maybe we could stuff something like this into some `packages/services/local-proxy`?

**Comment by rperryng** [comment]
I have been using the docker setup for any local development which doesn't need a proxy server (since everything communicates within the docker network), a proxy server would be nice for faster feedback on local development when trying to isolate the storage containers but the docker setup fulfills my needs, closing :)
