### ISSUE TITLE
Changelog Feed within hive app

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#3013]
On GitHub, there is a list of the latest changes within the UI.
<img width="795" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/f84c4d41-9382-408b-99ce-450115ede817">

It would be great to have something similar within the Hive app. We already expose a list of all changes via the changelog.json file.

**Comment by kamilkisiela** [comment]
@TuvalSimha it would be nice to display it in a format similar to https://headwayapp.co, not GitHub
