### ISSUE TITLE
Usage-report for special operation

### ISSUE THREAD

**Issue by Samjin** [kamilkisiela/graphql-hive#3016]
When error such as 'PERSISTED_QUERY_NOT_FOUND' happens, Hive report tool would throw. This is creating unnecessary noise in our log. 

Error message details
```
HIVE_USAGE_REPORTING_PLUGIN_ERROR
[hive][usage] Failed to send data: Request failed with status code 500

Failed to collect operation TypeError: Cannot read property 'name' of undefined at Object.Argument (/app/node_modules/@graphql-hive/client/cjs/internal/usage.js:265:64) at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27) at visit (/app/node_modules/graphql/language/visitor.js:197:21) at collect (/app/node_modules/@graphql-hive/client/cjs/internal/usage.js:241:29) at /app/node_modules/@graphql-hive/client/cjs/internal/utils.js:34:23 at complete (/app/n…
```

Can hive usage report bypass reporting issues from getting an operation string? 
eg. [Apollo report ](https://github.com/apollographql/apollo-server/blob/2f4b0343e35c7f1d3b4f0683dffc98950c2603f5/packages/server/src/plugin/usageReporting/plugin.ts#L473C1-L475C37)

**Comment by kamilkisiela** [comment]
#3017 should fix it
