### ISSUE TITLE
[HIVE CLI] Failed to publish schema -  Field "gitHub"   is not defined by type "SchemaPublishInput"

### ISSUE THREAD

**Issue by andriihrachov** [kamilkisiela/graphql-hive#3028]
Latest versions of CLI & Hive self hosted

```
Failed to publish schema
 ›   Error: Variable "$input" got invalid value { service: "****", 
 ›   url: "http://***********", 
 ›   author: "andriihrachov", commit: 
 ›   "e53a9f2f52414923a6122d9886fa1766b68ba53f", sdl: "extend schema ****", 
 ›   experimental_acceptBreakingChanges: false, gitHub: null }; Field "gitHub" 
 ›   is not defined by type "SchemaPublishInput". Did you mean "github"?
 ›   Reference: 0ca29f0a-7e44-4ed1-bb19-8858e7106c9e
```

probably related to [this PR](https://github.com/kamilkisiela/graphql-hive/pull/2701/files#diff-17000342e7d9b434c85ea1b0904ee2fedd1c2c6ec339b50bff9dc98a862a9e16R209) ??

**Comment by n1ru4l** [comment]
@andriihrachov Are you sure you are running the latest version of Hive? When upgrading the CLI you need to run the latest Hive version.

We currently have no great versioning solution for the self-hosted Hive. However, we will try to tackle that soon as part of https://github.com/kamilkisiela/graphql-hive/issues/2995.

**Comment by andriihrachov** [comment]
cleared docker cache (we use wrappers), rebuilt everything and re-deployed. problem solved, thanks !
