### ISSUE TITLE
Unused Schema: shows fields that are used, if *at least* one argument is unused

### ISSUE THREAD

**Issue by amanb014** [kamilkisiela/graphql-hive#3049]
## Problem Statement

Hello! I have some questions around Unused Schema and the intention. It seems like some of it is a bit misleading from our perspective, because fields that are used are showing up in the list. The intention of the page seems to be a true list of unused schema fields, which isn't true at the moment.

I want to see if it's worth making a fix for it (I am willing to contribute to code+tests).

Let's say we have this in our schema:
```graphql
Query {
  users(ids: [ID!], email: String!): [User!]!

  type User {
    names: Names!
  }

  type Names {
    name: String!
    nickname: String!
  }
}
```

And our usages are as follows:
```
query {
  users(ids: ["1"]) {
    names {
      name
    }
  }
}
```

From the above, I would expect that `users` would show as used, but in our data today, since argument `email: String!` is not used, the line item shows up in the "Unused schema" section:

```
Query.users(email: String!): [User!]!
```

Which is I am assuming is saying that `email` is unused, and though `ids` is used since it doesn't show up there.

## Contributions
I have this PR which I _think_ is on the right track, but I just want to make sure before I proceed further. First PR draft so I want to make sure it's not too far off, or that we agree to the goals listed above! 

DRAFT PR: https://github.com/kamilkisiela/graphql-hive/pull/3048

## Open Question
- Am I understanding the way the "Unused Schema" section works? 
- Should the fields that are used (with unused arguments) actually be showing up?

**Comment by kamilkisiela** [comment]
Hi, thanks for creating this issues.

> Should the fields that are used (with unused arguments) actually be showing up?

I know it’s confusing but how would you show an unused argument without the field?
I did thought about it when implementing this view.
If we don’t display a field the we can’t display an argument, but we could use some form of visual representation of unused field (the field could be of gray colour, or have a line through).

The thing is that we need to show unused arguments otherwise we show only part of the story and detecting unused arguments would be impossible.

**Comment by amanb014** [comment]
>how would you show an unused argument without the field?

I was thinking about this too. I think unfortunately it might require a UI change as well to make that a clear distinction.

Potentially, we can somehow make this functionality more clear by each row mentioning which part is unused?

Whether it's the arguments or it's the actual field definition.

**Comment by n1ru4l** [comment]
A schema coordinate for a field argument would be `Query.users(email:)`.
See https://github.com/graphql/graphql-spec/pull/794/files#diff-be72f083146e025cf29fd9dec772a7f903f50345ef472f451d51af0e6e44f78c

**Comment by kamilkisiela** [comment]
@n1ru4l we're talking about visual representation (the unused schema view).
