### ISSUE TITLE
Connect button is missing

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#31]
It should be available for all kind of projects

**Comment by alanquigley-toast** [comment]
Using a fresh install, self-hosted Hive - DOCKER_TAG=":23df2c05b7bc4c7f76d9110369a0cb71cda483f5"

Is the expectation that a Connect button should appear? I see no Connect button in any project type I've tried.

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/54547753/210791028-edb63ad1-947f-4ae3-bcc7-a85c96915fad.png">
