### ISSUE TITLE
Create and publish docker images

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#311]

**Comment by n1ru4l** [comment]
One interesting problem to solve will be the `NEXT_PUBLIC_XXXX` environment variables, as they must be set during build time. As a docker image user, I only want to pull the image and run it, not build it and embed the env variables from scratch.

The solution here can be to change all `NEXT_PUBLIC_XXXX` to normal environment variables and use the `_document.tsx` file for exposing the public environment variables to the frontend by embedding them within the `HTML` in a `<script>` tag, I think we can safely return the client env information via `getInitialProps`. (https://github.com/kamilkisiela/graphql-hive/blob/8a0e0cd300a59a4e8ad03a3673c585a78a34ac66/packages/web/app/pages/_document.tsx)

Then the docker image user simply has to provide all env variables to the docker container.

**Comment by n1ru4l** [comment]
Docker images will be published to the github container registry via https://github.com/kamilkisiela/graphql-hive/pull/386

**Comment by n1ru4l** [comment]
Docker images are now built for each commit via https://github.com/kamilkisiela/graphql-hive/pull/386

However, we still need a solution for releasing/promoting "stable" images (built from the `main` branch).

_____

Internal discussion link:
- https://tortilla-hq.slack.com/archives/C01E8ATBQGN/p1663836892258549
- https://www.youtube.com/watch?v=AvYnqI6EB5Y
