### ISSUE TITLE
Document how to use Docker images to self-host GraphQL Hive

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#312]
#311

**Comment by usama-gyg** [comment]
Any update on the documentation? Thanks in advance for looking into this.

**Comment by n1ru4l** [comment]
![Screenshot 2022-09-28 at 15 30 47](https://user-images.githubusercontent.com/14338007/193011829-c0a8861b-03f3-4883-b65d-9a858961ec11.png)

@usama-gyg 😉

**Comment by SpeedyGonzaless** [comment]
Hi! Is there any estimate date when this would be released?

**Comment by n1ru4l** [comment]
Today :)

**Comment by SpeedyGonzaless** [comment]
I am sorry for disturbing, but where can I find the guide for self-hosted solution that is on your screenshot? It is not [here](https://docs.graphql-hive.com/). Or it is not released yet?

**Comment by kamilkisiela** [comment]
We had to revert something but now it's back, check again.

**Comment by n1ru4l** [comment]
@SpeedyGonzaless Here you go: 
- Docs: https://docs.graphql-hive.com/self-hosting/get-started
- Blogpost: https://the-guild.dev/blog/announcing-self-hosted-graphql-hive
