### ISSUE TITLE
[dev-env] Next.js does not pick up changes from `@/foo/bar` imports

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#314]
My current workflow is the following (after a code change):

1. stop server
2. delete .next folder
3. start server

It is slow and makes me less productive :(

It seems like next.js has some issues when resolving/watching aliased imports.

**Comment by kamilkisiela** [comment]
Hmm, I'm working on Next.js right now and it works fine 🤔

**Comment by kamilkisiela** [comment]
`tsup` does not pick up changes but because it treats paths in `tsconfig.json` as external things.

**Comment by n1ru4l** [comment]
@kamilkisiela It seems to happen when you edit a file that is ONLY imported via `@/components/brrrt` in API route handlers.
