### ISSUE TITLE
allow passing http Agent for GraphQL Hive Client Apollo Server.

### ISSUE THREAD

**Issue by samuelAndalon** [kamilkisiela/graphql-hive#3255]
Hive Client which under the hood does http requests with axios and we need to keep alive tcp connections to avoid creating one each time we make a request, currently we are making a lot of `tcp.connect`.

axios allows passing an http.agent so we should be able to add that to the HiveClientConfig

![image](https://github.com/kamilkisiela/graphql-hive/assets/6611331/0da18d26-d030-47b1-9c27-6f0bc911fa3c)

**Comment by kamilkisiela** [comment]
Yes, it could be added [here](https://github.com/kamilkisiela/graphql-hive/blob/3670ab7040f0f7fad5b030af254ad56b9ed7aecc/packages/libraries/client/src/internal/agent.ts#L6)
