### ISSUE TITLE
Could not parse schema: UrlParse

### ISSUE THREAD

**Issue by rcrowe** [kamilkisiela/graphql-hive#330]
Hive will accept a sub-graph endpoint that does not include the scheme.

If you try running the router pointed at your Hive schema you'll receive the following error:
```
{"timestamp":"2022-09-01T16:17:48.902164Z","level":"ERROR","fields":{"message":"could not parse schema: UrlParse(\"name\", InvalidUri(InvalidFormat))"},"target":"apollo_router::state_machine"}
```

At first, that's a little cryptic on where the error lies, only until you spot the `name` & match that to the schema name in Hive is it clear.
We republished the schema, setting a URL with the `https://` scheme which resolved the issue.

Should Hive accept a URL for a sub-graph that isn't valid? If not, then this feels like a bug to me. Hive router can not serve a schema that was previously accepted and instead should have errored when we pushed a change.

**Comment by dotansimha** [comment]
I assume we need to add a check to verify the URL here? https://github.com/kamilkisiela/graphql-hive/blob/main/packages/services/api/src/modules/schema/providers/schema-publisher.ts#L315
