### ISSUE TITLE
Router panics when monitoring is enabled

### ISSUE THREAD

**Issue by rcrowe** [kamilkisiela/graphql-hive#331]
Followed the instructions here: https://docs.graphql-hive.com/features/monitoring#apollo-router
Setting the config to enable the plugin & setting the environmental variable `HIVE_TOKEN`.

The router starts up and seems fine, after firing a single request through the router, shortly after I get the following panic. I presume the delay comes from the buffer being flushed.

```
{"timestamp":"2022-09-01T16:54:24.131580Z","level":"ERROR","fields":{"message":"panicked at 'called `Option::unwrap()` on a `None` value', src/graphql.rs:41:64"},"target":"apollo_router::executable"}
```

The Hive router has been built against `v1.0.0-alpha.0`...

```
{"timestamp":"2022-09-01T16:59:50.436952Z","level":"INFO","fields":{"message":"Apollo Router v1.0.0-alpha.0 // (c) Apollo Graph, Inc. // Licensed as ELv2 (https://go.apollo.dev/elv2)"},"target":"apollo_router::executable"}
```

**Comment by kamilkisiela** [comment]
Can you share an example GraphQL operation? At some point, we had an issue with the query normalization logic and it was related to inline fragments.

**Comment by RMHonor** [comment]
This seems to work fine if there aren't any variables involved. This basic query with an inline argument is fine.

```graphql
query test {
  accountById(id: "foo") {
    id
  }
}
```

But if you introduce a variable, that's when it crashes:

```graphql
query test($id: String!) {
  accountById(id: $id) {
    id
  }
}
```

**Comment by kamilkisiela** [comment]
#342

**Comment by kamilkisiela** [comment]
> The Hive router has been built against v1.0.0-alpha.0...

it's built against the latest version of Apollo Router (of the time of the commit)
