### ISSUE TITLE
operations with @client directive failed to validate using operations:check in hive cli

### ISSUE THREAD

**Issue by jmvtrinidad** [kamilkisiela/graphql-hive#3379]
## Problem
Apollo has a default directive like [@client](https://www.apollographql.com/docs/react/data/directives/#client) which allows to add a custom resolver on the client side for the fields that is tag with this directive.
When using hive cli operations:check there is no way to pass the option for [validation](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/core/src/validate/index.ts#L47) so such operation check can be able to pass the validation
![Screenshot 2023-11-14 at 10 10 08 AM](https://github.com/kamilkisiela/graphql-hive/assets/7194300/187f0f1e-f8bc-4676-9d05-34b183741447)

**Comment by kamilkisiela** [comment]
Solved in https://github.com/kamilkisiela/graphql-hive/blob/main/packages/libraries/cli/CHANGELOG.md#0330
