### ISSUE TITLE
Feature Request: Filter schema checks by service

### ISSUE THREAD

**Issue by christophflick-toast** [kamilkisiela/graphql-hive#3389]
Hi!
It would be great if it was possible in the schema checks UI to filter by service, so you could see all the checks that happened for a specific service.

Apart from that, it would be great if the schema check filter would stay when opening a check. Currently, they reset to off when clicking on a new check.
![image](https://github.com/kamilkisiela/graphql-hive/assets/112861549/97addad7-c96f-464b-aa24-94f1e3088e94)

**Comment by n1ru4l** [comment]
> Apart from that, it would be great if the schema check filter would stay when opening a check. Currently, they reset to off when clicking on a new check.

This will be improved via https://github.com/kamilkisiela/graphql-hive/pull/3419.

**Comment by christophflick-toast** [comment]
Closed by #3419
