### ISSUE TITLE
Hive client failed to check shema and publish 

### ISSUE THREAD

**Issue by rrguhan6** [kamilkisiela/graphql-hive#3435]
After upgrading hive cli to 0.31.0, I am receiving the following error when running **hive schema:check location.graphql --service location_service**

```
✖ Failed to check schema
 ›   Error: Unknown argument "withSafeBasedOnUsageNote" on field "SchemaChange.message".
 ›   Reference: u8jQOQjuSSSaoT4NJFyZZg/0000000022
```

Hive cli Version: **@graphql-hive/cli/0.31.0 linux-x64 node-v18.18.2**

If i use **@graphql-hive/cli/0.30.4 linux-x64 node-v18.18.2** then its working 

Getting the same error while publishing too.

Please help us to resolve this. Is it possible to install hive cli binary with specific version? 

Thanks.

**Comment by n1ru4l** [comment]
Please upgrade your self-hosted GraphQL Hive version if you want to use the latest CLI version

**Comment by rrguhan6** [comment]
Is it possible to install older CLI ?

**Comment by n1ru4l** [comment]
Yes, you can install older versions of the CLI.
Just downgrade to your previous version (https://www.npmjs.com/package/@graphql-hive/cli?activeTab=versions)

The following should be fine. `@graphql-hive/cli@0.30.4`

**Comment by kamilkisiela** [comment]
@rrguhan6 https://the-guild.dev/graphql/hive/product-updates/2023-11-24-non-npm-cli-version-selection (if you're using install.sh script)

**Comment by rrguhan6** [comment]
Thanks!

**Comment by kamilkisiela** [comment]
little update, it's `HIVE_CLI_VERSION` not `VERSION` now.
