### ISSUE TITLE
Hive Usage: `exclude` argument to support RegExp

### ISSUE THREAD

**Issue by amanb014** [kamilkisiela/graphql-hive#3493]
Hello,

I have a feature request that would be pretty beneficial for us that involves excluding certain operations from being posted to Hive.

## What

The [current schema](https://github.com/kamilkisiela/graphql-hive/blob/189719eadaa61d0c28fa642a08bd6eb0bf1f41b3/packages/libraries/client/src/internal/types.ts#L72) here is:
```typescript
exclude?: string[];
```

Desired Schema:
```typescript
exclude?: Array<string | RegExp>
```

Example values:
```typescript
exclude: ['IntrospectionQuery', new RegExp('^Hello')]
```

## Why

There are certain operations that are prefixed or suffixed in our system that we use internally, and we have no benefit from posting this to Hive. 

In order to not make this a flaky list that always needs updating, it would be nice if we can match on regexp values along with perfect string matches.

## Breaking Change?
I don't think so!

**Comment by n1ru4l** [comment]
@amanb014 This seems useful! Are you open to helping us add this feature?
