### ISSUE TITLE
Starting from docker-compose and creating organization not possible atm

### ISSUE THREAD

**Issue by PlayAnyData** [kamilkisiela/graphql-hive#3547]
I have just checked out latest master version and it seems there are two issues:
1. Adding an organization comes with no default type set, leading to the following exception:
` originalError: error: null value in column "type" of relation "organizations" violates not-null constraint
at file:///usr/src/app/index.js:101816:21
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///usr/src/app/index.js:95242:24
at async executeQuery (file:///usr/src/app/index.js:93274:22)
at async query (file:///usr/src/app/index.js:95240:14)
at async one (file:///usr/src/app/index.js:96218:24)
[...]`
The error is located here:
https://github.com/kamilkisiela/graphql-hive/blob/487e3af201fc2b300e19550d48971d2cb226f222/packages/services/storage/src/index.ts#L573
2. Even if an organization_type is set, e.g. via PGAdmin, there is another issue:
`{"level":50,"time":1701950392334,"pid":1,"hostname":"19e6c1e5bd28","length":121,"name":"error","severity":"ERROR","code":"42703","position":"93","file":"parse_relation.c","line":"3638","routine":"errorMissingColumn","notices":[],"stack":"error: column om.connected_to_zendesk does not exist\n    at file:///usr/src/app/index.js:101816:21\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/index.js:95242:24\n    at async executeQuery (file:///usr/src/app/index.js:93274:22)\n    at async query (file:///usr/src/app/index.js:95240:14)\n    at async createConnection (file:///usr/src/app/index.js:98599:18)\n    at async file:///usr/src/app/index.js:219023:26","type":"Error","msg":"column om.connected_to_zendesk does not exist"}`

I can see here a migration: https://github.com/kamilkisiela/graphql-hive/blob/cba5b047e80787ebb0bbef7d96c10c3d1581fbab/packages/migrations/src/actions/2023.09.01T09.54.00.zendesk-support.ts#L12

However it is not executed for the initial build up of postgres.

**Comment by PlayAnyData** [comment]
Update: Not sure why this is happening, because there is no error or other indicator in log, but migrations seem to be stuck at: "2023.01.04T17.00.23.hobby-7-by-default.sql"

That's why there have been inconsistencies.

**Comment by PlayAnyData** [comment]
I can see there are no images created for migrations https://github.com/kamilkisiela/graphql-hive/pkgs/container/graphql-hive%2Fmigrations

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/blob/14c24f3fc7d9bcdb06d8cc528150999878128db6/docker/docker-compose.community.yml#L173-L174
it's `storage` image that does migrations

**Comment by PlayAnyData** [comment]
oh yes, you are right. Thanks for the pointer. I was searching for migrations the whole time.
