### ISSUE TITLE
Question: Can we miss usages data if sampleRate is less than 1.0?

### ISSUE THREAD

**Issue by amanb014** [kamilkisiela/graphql-hive#3586]
## Question: Can we miss usages data if sampleRate is less than 1.0?

I see that we can set a sampleRate here: https://the-guild.dev/graphql/mesh/docs/guides/hive

> sampleRate (type: Float) - Sample rate to determine sampling. 0.0 = 0% chance of being sent 1.0 = 100% chance of being sent Default: 1.0

Does this mean that we can be missing some data for low usage fields if the sample rate is less than 100%?

For example,
- `field_1` is used 100 times in 1 day
- `field_2` is used 1 time
- `samepleRate: 0.8` 

Is there a 20% chance that we have no usages for `field_2`?

**Comment by troycarlson** [comment]
yes

**Comment by kamilkisiela** [comment]
Here’s a whole chapter about sampling 
https://the-guild.dev/graphql/hive/docs/api-reference/client#sampling

There are more sampling possibilities than the one you mentioned. In your case the At Least Once Sampling is a good choice.

**Basic sampling**
With sampleRate option, you're able to control the sampling rate of the usage reporting. Setting it to 0.5 will result in 50% of the operations being sent to Hive. There is no guarantee that every operation will be reported at least once (see atLeastOnceSampler).

**Dynamic sampling**
GraphQL Hive client accepts a function that returns a number between 0 and 1. This allows you to implement dynamic sampling based on the operation's context.

**At-least-once sampling**
If you want to make sure that every operation is reported at least once, you can use the atLeastOnceSampler. Every operation is reported at least once, but every next occurrence is decided by the sampler.

**Comment by dotansimha** [comment]
Hi @amanb014 ! 
As @kamilkisiela said, you have full control over sampling strategy. If you want to ensure you collect each operation at least once, you should use the `atLeastOnceSampler`.
