### ISSUE TITLE
Failed to publish schema

### ISSUE THREAD

**Issue by deathemperor** [kamilkisiela/graphql-hive#3594]
CLI run:

```cmd
bunx hive schema:publish \ 
  --registry.accessToken xxx \
  schema.graphql
```

result:

```
✖ Failed to publish schema
 ›   Error: Unexpected error.
 ›   Reference: f5ec1abe-0236-4eb9-af02-ac84fc11107b
 ```

tried 5 times all failed with these ids:
7627e64a-5bca-4a2d-96de-3e4e4f1c03de
9e31e642-5357-4655-89e3-5dff3384b5ea
ebd0a448-e8eb-4e27-bd3d-1a0336f2b7fe

my org also crash when trying to access it while publishing schema

<img width="928" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/4255482/7c5e921c-4642-4b1f-b7ec-10e40253f1b6">

**Comment by dotansimha** [comment]
Hi @deathemperor ,
Are you using the self-hosted version of Hive? or do you use the Cloud version?

**Comment by kamilkisiela** [comment]
Here's a [fix](https://github.com/kamilkisiela/graphql-hive/pull/3595)

**Comment by deathemperor** [comment]
> Hi @deathemperor , Are you using the self-hosted version of Hive? or do you use the Cloud version?
> 
> I'm asking because if you are using the Cloud version, you can use the Support option and we'll have all the details to debug your issue :)

I'm using the Cloud version. I just joined didn't know there's that option. Also forgot to mention that my schema is 8MB large.

**Comment by dotansimha** [comment]
Thanks @deathemperor . We are going to test and ship @kamilkisiela 's fix to production soon :) Sorry for the inconvenience!

**Comment by dotansimha** [comment]
@deathemperor fix is deployed, can you please try again now? :)
