### ISSUE TITLE
GraphQL Hive CLI - returns invalid URL when publishing new schema to registry

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#361]
When i do a `hive:publish`  i receive the URL that is slightly invalid:

```bash
dave@cookieMr:~/project-x$ hive schema:publish --service project-x "src/main/resources/schema/**/*.graphql*" --force

[...]

✔ Schema published (forced)
ℹ Available at https://app.graphql-hive.com/project-x/project-x/development/history/12345678-abcd-1234-abcd-1234567890ab
```

it seems that the produced URL doesn't follow the pattern `https://app.graphql-hive.com/:org/:project/:target` (seems like it uses `:product` twice and no `:org`.

Finish this by hand and pasting such fixed URL to a web browser works.

* Actual URL (wrong): `https://app.graphql-hive.com/project-x/project-x/development/history/12345678-abcd-1234-abcd-1234567890ab`
* Expected URL: `https://app.graphql-hive.com/org-x/project-x/development/history/12345678-abcd-1234-abcd-1234567890ab`

**Comment by kamilkisiela** [comment]
here :( https://github.com/kamilkisiela/graphql-hive/blob/985c25edd64f781d07ff3d58987144e93486380d/packages/services/api/src/modules/schema/providers/schema-publisher.ts#L612

Could you create a pull request? I know it's an easy fix but this could be your contribution to the project :)

**Comment by cookieMr** [comment]
Big THX to you @kamilkisiela for this fix (and for this entire project).
As always, keep up the good work and stay awesome :)

**Comment by kamilkisiela** [comment]
thanks <3 
It's should be soon in production 
https://github.com/kamilkisiela/graphql-hive/deployments/activity_log?environment=production
