### ISSUE TITLE
Make deprecations better visible in Hive

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#3666]
It would be nice to visibly see that fields/arguments are deprecate and shouldnt be used. 

It's not a concrete feature request and i'd love to get your insights here.

What im thinking of is something along the lines of .. a strikethrough of a field/argument in the explorer and if you hover it, it shows you the reason of deprecation.

(Below is just brainstorming ideas)
- As an addition it would be cool to be able to figure out what service is using which deprecated fields. 
- Or maybe export the deprecated fields per service on a periodic basis to mail teams on a weekly term to aid in getting rid of deprecations
- ...

Would love to hear your thoughts

**Comment by kamilkisiela** [comment]
We do now have a strikethrough of a field if it's deprecated, and we also have a dedicated page where only deprecated part of schema is presented
