### ISSUE TITLE
API token provided by The Hive Page (Target Settings tab) doesn't work with express+client

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#375]
1. create an API token as described in [Managing Tokens
](https://docs.graphql-hive.com/features/tokens) (as shown in the last screen shot there this is an API token). Copy it's value (`YOUR-TOKEN` will be used as the value for this issue).
2. Hook up the Hive Client in an express app as described in [Other Servers](https://docs.graphql-hive.com/features/monitoring#other-servers).
```javascript
const hive = createHive({
  enabled: true,
  debug: true,
  token: 'YOUR-TOKEN',
  usage: true
})
```
3. Run the server with hive client configured.
4. In logs i can observe `[hive][usage] Failed to send data (HTTP status 400): Authentication failed.`.

When changing the header from `Authentication: Bearer YOUR-TOKEN` to be `'X-API-Token': YOUR-TOKEN`, then i can see that usage statistics are successfully sent to target in the cloud hive. And the Operation tab statistics are updated correctly. I did this since this is how i was able to send usage data via REST ([as described in documentation](https://docs.graphql-hive.com/specs/usage-reports#curl-example-request)).

I am using latest version of [hive-client](https://www.npmjs.com/package/@graphql-hive/client) dependency (`npm i @graphql-hive/client@0.18.3`).

---

The question is: should i encode (somehow) my `YEAR-TOKEN` with JWT?

**Comment by kamilkisiela** [comment]
That's super weird. We do get the requests with the `authorization` header.

You're referring to our Cloud or your self-hosted instance? Maybe it expects `authorization` and in your setup it's not lower cased.

**Comment by cookieMr** [comment]
I agree it's super weird. You are working on this project for so long, that such issue should be spotted already. So i might be doing something wrong :) 

In the PR i assigned to this issue i see `axios.post()` so i assume it should match the curl REST command (i am talking about headers):
```bash
curl --request POST \
  --url https://app.graphql-hive.com/usage \
  --header 'X-API-Token: YOUR_TOKEN' \
  --header 'Content-Type: application/json' \
  -d '{
  "size": 1,
  "map": {
    "c3b6d9b0": {
      "operationName": "userTransfers",
      "operation": "query magic { id }",
      "fields": ["Query", "Query.magic", "Magic.id"]
    }
  },
  "operations": [
    {
      "operationMapKey": "c3b6d9b0",
      "timestamp": 1663145563000,
      "execution": {
        "ok": true,
        "duration": 150000000,
        "errorsTotal": 0
      },
      "metadata": {
        "client": {
          "name": "demo",
          "version": "0.2"
        }
      }
    }
  ]
}'
```

**Comment by kamilkisiela** [comment]
It works for me:

```bash
curl --request POST \
  --url https://app.graphql-hive.com/usage \
  --header 'Authorization: Bearer XYZ' \
  --header 'Content-Type: application/json' \
  -d '{
  "size": 1,
  "map": {
    "op1": {
      "operationName": "AuthorizationBearer",
      "operation": "query magic { AuthorizationBearer }",
      "fields": ["Query", "Query.magic", "Magic.AuthorizationBearer"]
    }
  },
  "operations": [
    {
      "operationMapKey": "op1",
      "timestamp": 1663328619590,
      "execution": {
        "ok": true,
        "duration": 150000000,
        "errorsTotal": 0
      },
      "metadata": {
        "client": {
          "name": "demo",
          "version": "0.2"
        }
      }
    }
  ]
}'

curl --request POST \
  --url https://app.graphql-hive.com/usage \
  --header 'authorization: Bearer XYZ' \
  --header 'Content-Type: application/json' \
  -d '{
  "size": 1,
  "map": {
    "op2": {
      "operationName": "authorizationBearer",
      "operation": "query magic { authorizationBearer }",
      "fields": ["Query", "Query.magic", "Magic.authorizationBearer"]
    }
  },
  "operations": [
    {
      "operationMapKey": "op2",
      "timestamp": 1663328619590,
      "execution": {
        "ok": true,
        "duration": 150000000,
        "errorsTotal": 0
      },
      "metadata": {
        "client": {
          "name": "demo",
          "version": "0.2"
        }
      }
    }
  ]
}'


curl --request POST \
  --url https://app.graphql-hive.com/usage \
  --header 'x-api-token: XYZ' \
  --header 'Content-Type: application/json' \
  -d '{
  "size": 1,
  "map": {
    "op3": {
      "operationName": "xapitoken",
      "operation": "query magic { xapitoken }",
      "fields": ["Query", "Query.magic", "Magic.xapitoken"]
    }
  },
  "operations": [
    {
      "operationMapKey": "op3",
      "timestamp": 1663328619590,
      "execution": {
        "ok": true,
        "duration": 150000000,
        "errorsTotal": 0
      },
      "metadata": {
        "client": {
          "name": "demo",
          "version": "0.2"
        }
      }
    }
  ]
}'
```

I see `AuthorizationBearer`, `authorizationBearer` and `xapitoken` operations in Hive

**Comment by kamilkisiela** [comment]
I'm interested in how you're using GraphQL Hive, do you think we (The Guild) could schedule a meeting with you?

**Comment by cookieMr** [comment]
@kamilkisiela thx for the offer of a meeting
but for now let me do some more tests on my local with the code i have

i can confirm that running the same curl request with either `--header 'Authorization: Bearer XXX` or `--header 'X-API-Token: XXX` everything works. Let me take a deeper look into the code before we'll reach out for more help.

**Comment by cookieMr** [comment]
Since both #376 and #377 are closed (merged or resolved without merge) this issue can be closed.
In case of future issues we can reopen this one.
