### ISSUE TITLE
Feature Request: Separate Dangerous Changes from Warnings in Hive CLI Command

### ISSUE THREAD

**Issue by kongMina** [kamilkisiela/graphql-hive#3793]
👋 We have a feature request to improve the output from the yarn CLI command, `yarn hive schema:check` to categorize changes as breaking , dangerous or safe changes as it is currently being done in Slack alerts

## Context

The current output of `yarn hive schema:check` looks like:
```
Detected 3 changes:

- Field foo was added to object type HelloWorld
- Field bar was added to object type HelloWorld
- Field baz was added to object type HelloWorld
```
Like the Slack alerts output, we would like the output to look like:
```
Detected 3 changes:

Breaking changes
- Field foo was added to object type HelloWorld

Dangerous changes
- Field bar was added to object type HelloWorld

Safe changes
- Field baz was added to object type HelloWorld
```

We currently leverage the CLI command to print the output directly into PR comments for developers to see when there are changes to the schema. However, it's unclear in the current output whether there is a dangerous change or not. It would be really great if we could have this distinction between changes

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/pull/3862
