### ISSUE TITLE
`useHive` client plugin skip reporting for operation/request based on context value

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#3810]
RIght now it is not possible to skip a single GraphQL request from usage reporting based on the context value or request headers. E.g. you would not want to track requests that are sent from a dev client, where production clients should always be tracked.

**Comment by kamilkisiela** [comment]
```typescript
usage: {
  sampler(context) {
    // context.contextValue
  },
}
```

https://the-guild.dev/graphql/hive/docs/api-reference/client#dynamic-sampling

**Comment by n1ru4l** [comment]
docs are nor clear, reopening until we document that you can access GraphQL context and request headers in there, this is a reuccuring question from a lot of folks

**Comment by kamilkisiela** [comment]
it's now explaining the sampling context
