### ISSUE TITLE
Cannot get docker tag from package on github

### ISSUE THREAD

**Issue by pierrebiver** [kamilkisiela/graphql-hive#3895]
We are self-hosting Hive and we cannot access the list of package that contains the docker tag in order to update our self-hosted Hive anymore. [https://github.com/users/kamilkisiela/packages/container/package/graphql-hive%2Fserver](https://github.com/users/kamilkisiela/packages/container/package/graphql-hive%2Fserver) Accessing this URL is giving us an error on github, are they now private ? did we miss something ?

**Comment by n1ru4l** [comment]
This seems to be an issue with GitHub, https://github.com/kamilkisiela?tab=packages&repo_name=graphql-hive is accessible.

However, once I click on a specific container I get an error page...

![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/e1002988-6287-4a9e-8d58-466a451bf25c)

**Comment by pierrebiver** [comment]
ah so you get the same error, its been there for a while but I found that some package are accessible so its fine, but thanks for the answer.
