### ISSUE TITLE
revisit all eslint-ignore process.env comments

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#409]
We should only access `process.env` in the entry point of an application/library using a decoding/validation approach as introduced via https://github.com/kamilkisiela/graphql-hive/pull/398.

**Comment by dotansimha** [comment]
@B2o5T any idea how to enforce/implement such check?

**Comment by kamilkisiela** [comment]
We no longer use `// eslint-disable-next-line no-process-env` is random places.
