### ISSUE TITLE
Auto delete 'insights' data (clickhouse) older than X 

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#4120]
I'd like clickhouse data to be auto deleted after a certain amount of time to keep the volume limited

Basically im curious if clickhouse data is auto deleted already after X or if i have to enable it somewhere or last if neither of those is the case i'd like to request this as a feature to auto-delete data older than X

**Comment by kamilkisiela** [comment]
We do have TTL on tables and views. Daily aggregation views get TTL equal to retention period of usage reports, hourly agg is deleted after 60 days I believe and minutely agg lives for an hour or something.
