### ISSUE TITLE
app install node_modules in docker image with lockfile

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#421]
Right now the dependencies for the `app` docker image are installed without a lockfile.
This is dangerous.
We can instead generate a lockfile from the mono-repo lockfile using https://www.npmjs.com/package/generate-lockfile

**Comment by kamilkisiela** [comment]
@enisdenjo @n1ru4l can it be closed now, with the new pnpm setup?

**Comment by enisdenjo** [comment]
We now use the [deploy command](https://pnpm.io/cli/deploy) to create a `node_modules` folder inside the `dist` folder containing the necessary dependencies as per the lockfile ([see here](https://github.com/kamilkisiela/graphql-hive/blob/6305788f931867f9cbd2a09a2eb7312b8f6cb9e0/packages/web/app/package.json#L10)).
