### ISSUE TITLE
date ranger filter: suggest custom number interval

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#4229]
we have predefined (fixed) presets within the date range picker.

![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/ee597f73-e33d-4f74-ac4f-ace7771539bd)

In case we put in a number, we should also generate on-the-fly possible options for the given time range.

E.g if you enter `last 4`, we could automatically display:
- last 4 minutes
- last 4 hours
- last 4 days
- last 4 months

Sentry does this for example:
![image](https://github.com/kamilkisiela/graphql-hive/assets/14338007/5c561475-4cc8-471b-a96c-02e2dc3b46f6)

From a technical perspective we can just check whether the input string starts with `last <number>`, and then automatically add the ranges (minutes, hours, days, weeks, month) based on the user retention range.

**Comment by dotansimha** [comment]
done in https://github.com/kamilkisiela/graphql-hive/pull/4594
