### ISSUE TITLE
When signing in via GitHub and Google account to GraphQL Hive results in 2 different accounts

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#424]
1. When i sign in to GraphQL Hive ([at sing in page](https://app.graphql-hive.com/auth?rid=thirdpartyemailpassword&redirectToPath=)) via Google account,
1. then i create a new project/targets (do some changes to be persisted),
1. then i sing out,
1. then i sign in to o GraphQL Hive ([at sing in page](https://app.graphql-hive.com/auth?rid=thirdpartyemailpassword&redirectToPath=)) via GitHub account (which is registered under the same email as the Goolge sign in account)
    * [actual] i end up as a different user (and i see no org/projects set up when logged in with Google account)
    * [expected] i should end up in the same org/project with the same targets as in Google and GitHub account sign in. After all they were registered under the same email account (gmail account).
1. and then if i sign in back with Google (as in 1st step) i see all projects/org i set up there.

THe question here is: is it possible to log in via multiple different method (Google, GitHub, login+pass) to the same account if they have the same email.

**Comment by kamilkisiela** [comment]
The reason for it that you could potentially change your email address in GitHub to `kamil.kisiela@gmail.com`, sign in with GitHub and be recognized as me. I know it's not perfect and we could add account merging by email verification, but that's a different story.

**Comment by cookieMr** [comment]
ok, i see, valid point.

let me do a quick test on login+pass and Google SSO (this shouldn't allow messing up emails by users) - do you allow user to change his email after account creation?

**Comment by cookieMr** [comment]
Logging with login(email)+pass recognizes me as a different user than when i log in via Google SSO (under the same email as with login+pass).

1. Google SSO (my personal email)
1. login+pass )login is my personal email, same as step above)
Result is that these are 2 different accounts.

So I will ask the same question again, should these two logins attempts result in a person having 1 or 2 accounts?

**Comment by n1ru4l** [comment]
In 2 accounts, there is no account merging between password+email, GitHub, and Google.
