### ISSUE TITLE
Search Operation requires random prefix to find the same kind of operation

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#425]
When i try to find an operation at `https://app.graphql-hive.com/:org/:project/:target/operations?period=30d`
then i need to use random 4-char prefix
but i cannot find the same operation (in this e.g. `Query`) by typing its name.

I need to find each `Query` by scrolling thru whole dropdown in `Filter by operation`.

![Screenshot from 2022-09-29 15-51-35](https://user-images.githubusercontent.com/8577083/193050344-857a5587-5318-4412-ba0f-056a619875ae.png)
![Screenshot from 2022-09-29 15-51-47](https://user-images.githubusercontent.com/8577083/193050350-a28c3d7b-c8e5-49d8-b751-bd28a325496a.png)
![Screenshot from 2022-09-29 15-52-25](https://user-images.githubusercontent.com/8577083/193050354-665db5d4-ac39-4c1e-a71a-bc60d295b156.png)

**Comment by kamilkisiela** [comment]
No need to type the prefix, it's just that the search term has no `toLowerCase()` applied.

![Zrzut ekranu 2022-10-5 o 12 16 31](https://user-images.githubusercontent.com/8167190/194037650-15fd2fce-b87c-4f99-ad63-0b80082e1c3d.png)

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-hive/pull/451
