### ISSUE TITLE
Cannot set a role different than viewer

### ISSUE THREAD

**Issue by klys-equinix** [kamilkisiela/graphql-hive#4290]
Hi, I have started this as discussion:
https://github.com/kamilkisiela/graphql-hive/discussions/4271
But it looks like a bug to me

I added several users to my organization. When i want to invite more, i can only select the Viewer role:
![image](https://github.com/kamilkisiela/graphql-hive/assets/20441031/84f81839-3b9b-4a4f-b353-26c63370423f)

**Comment by kamilkisiela** [comment]
I think it's solved, can you check again?

**Comment by klys-equinix** [comment]
Yes, fixed, thanks a lot :)
