### ISSUE TITLE
Evaluate vite/vite-plugin-ssr as a Next.js replacement

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#430]
The Next.js developer experience is utterly painful. Long loading times and frequent dev server crashes reduce productivity.

https://vite-plugin-ssr.com/

**Comment by dotansimha** [comment]
@B2o5T what do you think?

**Comment by kamilkisiela** [comment]
#4288 one step closer

**Comment by kamilkisiela** [comment]
#4612
