### ISSUE TITLE
persist insights operation/client filter in url

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#4368]
We are not persisting the client/operation filters on the insights page within the URL query parameters.
We should do it, as this will make sharing the link with other people easier.

<img width="660" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/ebfc493f-76fb-485b-a41c-c41578fe9975">

**Comment by kamilkisiela** [comment]
Not sure about the operations filter to be honest, this could be a very long list and we could hit the URL length limit

**Comment by rickbijkerk** [comment]
Just the client would already be a nice feature for us!

**Comment by n1ru4l** [comment]
closed via https://github.com/kamilkisiela/graphql-hive/pull/5617
