### ISSUE TITLE
CORS Issues with Deployed GraphQL Hive

### ISSUE THREAD

**Issue by Dan6erbond** [kamilkisiela/graphql-hive#4479]
Hi, I'm trying to deploy GraphQL Hive on my K8s cluster.

I have the server running on api.hive.example.com, app on hive.example.com and usage on usage.hive.example.com.

The app's env includes:

```env
APP_BASE_URL=https://hive.example.com
GRAPHQL_PUBLIC_ORIGIN=https://api.hive.example.com
GRAPHQL_PUBLIC_ENDPOINT=https://api.hive.example.com/graphql
```

The same env is applied to the server, with `WEB_APP_URL` set to https://hive.example.com, but when I try to log in the requests to api.hive.example.com fail on preflight. This is clearly a CORS issue, but I would assume that configuring `WEB_APP_URL` in the server should resolve this issue, yet it doesn't.

Am I missing something?

**Comment by kamilkisiela** [comment]
How about server's env?

```env
WEB_APP_URL=?
GRAPHQL_PUBLIC_ORIGIN=?
```

**Comment by Dan6erbond** [comment]
Nevermind, this was my bad with the reverse proxy config. Closing...
