### ISSUE TITLE
Self-hosted: Apollo Federation: Unable to use schema with @external

### ISSUE THREAD

**Issue by yogeshcbsi** [kamilkisiela/graphql-hive#4642]
I have been trying to host schema created with Apollo Federation into self hosted Hive but seems like Hive is not composing super-graph correctly when `@external` is used in schema. Super-graph schema cannot used due to this issue

Example: Schema defined in `subgraph1` sub-graph as below:
```
name: String! @external
```

Results in `subgraph2` sub-graph schema:
```
name: String! @join__field(graph: SUBGRAPH2)
```

Expecting it to be resulted in below supergraph schema:
```
name: String! @join__field(graph: SUBGRAPH2) @join__field(graph: SUBGRAPH1, external: true)
```

This is field is implemented as part of interface in both subgraphs.

**Comment by kamilkisiela** [comment]
I feel like I need a small reproduction here (SDLs), I can't tell if it's an issue or not based only on informations provided by you.
I don't know how you implement an interface, I don't know if an interface has a `@key` directive, and if so what fields are part of it etc. There's a lot of missing things here for me to verify it.
