### ISSUE TITLE
Apollo Router does not work with rust 1.78

### ISSUE THREAD

**Issue by kindermax** [kamilkisiela/graphql-hive#4796]
Hi, recently renovate bot updated rust in `docker/router.dockerfile` to rust 1.78
https://github.com/kamilkisiela/graphql-hive/commit/b87e1a1496a5e904cebe5c663ddcb031fd711dd6

But turns out this version or rust is not supported by apollo router yet https://github.com/apollographql/router/issues/5084

Probably https://github.com/kamilkisiela/graphql-hive/commit/b87e1a1496a5e904cebe5c663ddcb031fd711dd6
should be reverted ?

Thank you

**Comment by kamilkisiela** [comment]
Thanks :)
