### ISSUE TITLE
Unable to open Stripe billing page

### ISSUE THREAD

**Issue by comatory** [kamilkisiela/graphql-hive#4907]
![Screenshot 2024-06-03 at 14 52 07](https://github.com/kamilkisiela/graphql-hive/assets/5990424/e4ee962b-31ae-4dce-b284-59fa6b4bf676)

"Stripe billing dashboard" button does not work for me. The returned response from contains `generateStripePortalLink`, when I use that link, it opens up fine when pasted into new browser tab. However something blows up when clicking the button, probably it's in the Javascript app. I'm getting this error in the console when clicking the button:

```
Error: Invariant failed
    at Oc (index-BtbdG_OP.js:41:61088)
    at oLt.navigate (index-BtbdG_OP.js:57:25166)
    at index-BtbdG_OP.js:5082:786
```

I am on managed version of Hive, it happens in release `04733c9fc7adb204b2d05e32b7746b89f38a7385`

**Comment by dotansimha** [comment]
Related: https://github.com/kamilkisiela/graphql-hive/issues/4915
