### ISSUE TITLE
Server crash when querying non-existing field using Apollo Server with @graphql-hive/apollo plugin

### ISSUE THREAD

**Issue by silademirhan** [kamilkisiela/graphql-hive#4935]
### Description

I am experiencing a crash when a user sends a GraphQL request that includes a non-existing field. I am using `apollo-server-express` with the `@graphql-hive/apollo` plugin version `0.33.0`.

### Environment

- **GraphQL Hive Plugin Version**: `@graphql-hive/apollo` `0.33.0`
- **Apollo Server Version**: `apollo-server-express` `3.10.3`
- **Node.js Version**: `20.11.1`

### Steps to Reproduce

1. **Set up an Apollo Server with the Hive plugin as follows**:
    ```javascript
    import { ApolloServer } from 'apollo-server-express';
    import { useHive } from '@graphql-hive/apollo';

    const server = new ApolloServer({
        plugins: [
            useHive({
                enabled: true,
                token: 'HIVE_TOKEN',
                usage: true,
                selfHosting: {
                    usageEndpoint: 'https://your-usage-endpoint',
                    graphqlEndpoint: 'https://your-graphql-endpoint',
                    applicationUrl: '',
                },
                debug: false,
            }),
        ]
    });

    await server.start();
    ```

2. **Send a GraphQL query with a non-existing field, such as**:
    ```graphql
    query GetNonExistingField {
        someType {
            nonExistingField
        }
    }
    ```

3. **Observe the server crash with the following error log**:
    ```
    Error: Could not find a field definition of a field at someType.nonExistingField
        at Object.Field (/node_modules/@graphql-hive/core/cjs/client/usage.js:332:27)
        at Object.enter (/node_modules/graphql/utilities/TypeInfo.js:391:27)
        at visit (/node_modules/graphql/language/visitor.js:197:21)
        at collect (/node_modules/@graphql-hive/core/cjs/client/usage.js:324:29)
        at async captureAsync (/node_modules/@graphql-hive/core/cjs/client/agent.js:39:21)
    ```

### Expected Behavior

- The Hive plugin should gracefully handle the error caused by a non-existing field in the query. The server should log the error and continue to function, possibly returning an appropriate error message to the client.

### Actual Behavior

- The server crashes with the error `Error: Could not find a field definition of a field at someType.nonExistingField`. This happens inside the `willSendResponse` lifecycle of the Hive plugin, preventing any further response handling.

### Additional Context

The field nonExistingField does not exist in the schema, which appears to cause the Hive plugin to fail during its processing.
It seems that apollo-server-express might be passing errors in a way that the Hive plugin does not handle gracefully, leading to a crash.

**Comment by hoanghun** [comment]
Also experiencing this with following versions:

- GraphQL Hive Plugin Version: `@graphql-hive/apollo 0.33.0`
- Apollo Server Version: `@apollo/server 4.9.3`
- Node.js Version: `18.17.1`
