### ISSUE TITLE
[landing-page] blog (and following) links has wrong styles

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#495]
They seem to have additional padding/marging

![Screenshot 2022-10-17 at 11 41 34](https://user-images.githubusercontent.com/14338007/196145246-0ff2cbdb-9aed-4f29-9072-c6e72ce9504b.png)

![image](https://user-images.githubusercontent.com/14338007/196145044-4be2d21d-ec80-4b19-b05e-71c37052e733.png)

**Comment by kamilkisiela** [comment]
We have it on all websites that are not on nextra yet. @B2o5T will fix it soon (#467)
