### ISSUE TITLE
Unable to run Hive with a domain containing .local

### ISSUE THREAD

**Issue by danielreynolds1** [kamilkisiela/graphql-hive#4981]
I've been trying to self-host Hive on a network where the domain name has to contain .local.
Whilst it starts, I am unable to login/register as I get an error that the apiDomain doesn't have a correct value.

I believe it is related to [this issue](https://github.com/supertokens/supertokens-node/issues/823) in Supertokens.

**Comment by saihaj** [comment]
looks like it was resolved https://github.com/supertokens/supertokens-node/issues/823#issuecomment-2076659219
