### ISSUE TITLE
Unable to submit support tickets

### ISSUE THREAD

**Issue by saihaj** [kamilkisiela/graphql-hive#5180]
Getting a GraphQL Mutation error when trying to submit a support ticket.

![CleanShot 2024-07-08 at 13 58 43@2x](https://github.com/kamilkisiela/graphql-hive/assets/44710980/ad058cd1-9355-4c2b-9cc9-0d50b23f7d7b)

**Comment by n1ru4l** [comment]
This seems to be the source of the error https://github.com/kamilkisiela/graphql-hive/blob/c9ef2d6aed7733a08748bb8fb8a25134ef9a2ed5/packages/services/api/src/modules/support/providers/support-manager.ts#L145-L187

https://hiveprod.grafana.net/explore?schemaVersion=1&panes=%7B%22r31%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer_name%3D%5C%22graphql-api%5C%22%7D%20%7C%3D%20%602cd4bd7d-9e52-9678-963f-f012f795b1a6%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1
