### ISSUE TITLE
Supergraph endpoint is not exposed in self-hosted variant

### ISSUE THREAD

**Issue by rickbijkerk** [kamilkisiela/graphql-hive#544]
If you self host Hive the supergraph is not exposed through any endpoint which blocks you from using it in a gateway such as the ones described here: https://docs.graphql-hive.com/features/registry-usage

**Comment by n1ru4l** [comment]
As a potential quick solution, we can expose this feature as an API endpoint on the `server` container.

**Comment by rickbijkerk** [comment]
That would work for us ^

**Comment by n1ru4l** [comment]
After some internal discussion, the following seems like a reasonable action plan:

Abstract the storage (Cloudflare KV) into an interface that has a Postgres and CF CV implementation.

Ship the worker code under a route on the hive server by using a w3c response/request adapter (https://github.com/ardatan/whatwg-node).

That way we can share the implementation on both Cloudflare workers and our server service.

An additional benefit of this is that in case of a Cloudflare Incident the server endpoint implementation can serve as a fallback - and of course it is the go-to solution for self hosted :)


Internal discussion: https://tortilla-hq.slack.com/archives/C01E8ATBQGN/p1667454454771289

**Comment by n1ru4l** [comment]
Related https://github.com/kamilkisiela/graphql-hive/issues/544

**Comment by n1ru4l** [comment]
Related https://github.com/kamilkisiela/graphql-hive/issues/622

**Comment by rickbijkerk** [comment]
_"As a potential quick solution, we can expose this feature as an API endpoint on the server container."_ 
Is this above still the plan for the 'quick fix' or do you straight go for the proper implementation.

Any rough estimate on the ETA?

**Comment by n1ru4l** [comment]
Hey @rickbijkerk, we are currently debating on an alternative (more sustainable approach), over here: https://github.com/kamilkisiela/graphql-hive/issues/622#issuecomment-1308478243

Any feedback would be highly appreciated. Once the decission has been made the implementation should be pretty straight-forward.

**Comment by n1ru4l** [comment]
@rickbijkerk https://github.com/kamilkisiela/graphql-hive/pull/692 is almost ready and will be merged to `main` soon.

**Comment by n1ru4l** [comment]
Hey everyone here, this is now documented on https://docs.graphql-hive.com/features/high-availability-cdn

Instead of using `https://cdn.graphql-hive.com` as the domain use `http://localhost:8082` as the base domain.

Please make sure you are using the latest `docker-compose.community.yml` file.
