### ISSUE TITLE
Question: How to modify logs emitted by hive?

### ISSUE THREAD

**Issue by arcadia-dutchie** [kamilkisiela/graphql-hive#5570]
Hello, I'm seeing error logs appearing in Splunk that contain stack traces and are being split onto multiple lines. I asked in [another issue](https://github.com/kamilkisiela/graphql-hive/issues/1227), but I'd really appreciate if someone could help me understand how to set up a `hiveApollo` client object with a `logger` option.  I've already got a logger using `winston` that JSON-encodes errors and would like for my Hive client to use that.

**Comment by kamilkisiela** [comment]
Hi, you can try:

```js
{
  agent: {
    logger: yourLogger
  }
}
```

and here's [the `Logger` interface](https://github.com/kamilkisiela/graphql-hive/blob/288e4e6b6c75902ef7f113bf3d4ca455d16d636d/packages/libraries/core/src/client/types.ts#L70-L73).

**Comment by arcadia-dutchie** [comment]
This worked like a charm. Thank you very much!
