### ISSUE TITLE
Composition errors are not shown to users

### ISSUE THREAD

**Issue by yanns** [kamilkisiela/graphql-hive#5628]
I'm trying to compose a schema, and the only error I get in the UI is "Unexpected composition error."
There are no details.

<img width="622" alt="Screenshot 2024-09-30 at 15 43 16" src="https://github.com/user-attachments/assets/af4c4a11-d228-458d-b336-79724def53d3">

The only way to get more information seems to activate external composition so that I can have a look at the errors inside the composition tool.

**Comment by yanns** [comment]
Same problem using hive check:
```
✖ Detected 1 error

   - Unexpected composition error.

View full report:
[...]
```

**Comment by yanns** [comment]
By using a self-hosted version, I could get the logs from `docker logs hive-schema-1`:
```
{"level":50,"time":1727710939026,"pid":7,"hostname":"f390b22bbbf1","reqId":"50Tq65Q3TGyEKMGwQR6+iQ/0000000030","err":{"type":"Error","message":"Directives on \"EnumTypeDefinition\" types are not supported yet","stack":"Error: Directives on \"EnumTypeDefinition\" types are not supported yet\n    at Object.Directive (file:///usr/src/app/@hive/schema/index.js:170486:23)\n    at Object.enter (file:///usr/src/app/@hive/schema/index.js:110742:123)\n    at Object.enter (file:///usr/src/app/@hive/schema/index.js:171770:27)\n    at visit (file:///usr/src/app/@hive/schema/index.js:110663:78)\n    at validateSubgraph (file:///usr/src/app/@hive/schema/index.js:174924:31)\n    at file:///usr/src/app/@hive/schema/index.js:181645:58\n    at Array.map (<anonymous>)\n    at validate (file:///usr/src/app/@hive/schema/index.js:181645:43)\n    at composeServices (file:///usr/src/app/@hive/schema/index.js:181675:28)\n    at composeFederationV2 (file:///usr/src/app/@hive/schema/index.js:182540:20)"},"msg":"Directives on \"EnumTypeDefinition\" types are not supported yet"}
```
It'd be great if those kind of information are pushed back to the users.

**Comment by dotansimha** [comment]
Hi @yanns , thank you for reporting this. From the original issue, I understand that you saw this error on the Cloud version of Hive?

**Comment by yanns** [comment]
Hi @dotansimha 

yes I originally saw this in the cloud version of hive.
I can reproduce the issue locally when running a local version with docker compose. With the local version, I could get more info by looking at the logs of the container `hive-schema-1`.

**Comment by dotansimha** [comment]
Thanks. I think the error originates in our composition library: https://github.com/the-guild-org/federation 
@kamilkisiela @n1ru4l will investigate, thank you for the detailed report! 🙇

**Comment by kamilkisiela** [comment]
Fix is in production

**Comment by kamilkisiela** [comment]
Yes but other errors are assertions, so no need to report them to the user.

**Comment by yanns** [comment]
the first screenshot I show is pretty unhelpful for users. So it'd be good to show some details about the errors no?

**Comment by kamilkisiela** [comment]
Is `expected Foo to be object type` helpful for a user? I don't think so, because it's an assertion and it's a bug in code, not a composition error. This is one example, but the rest of errors thrown in the composition library are similar.

**Comment by yanns** [comment]
The message `Directives on "EnumTypeDefinition" types are not supported yet` would have been useful.

**Comment by kamilkisiela** [comment]
but there's no longer such error, it was implemented

**Comment by yanns** [comment]
> but there's no longer such error, it was implemented

Yes I know.
My point was: when the error was still here, it'd have been good to see it as a user, and not having to spin up a local environment just to be able to check for logs on some container.
The error reporting could maybe be enhanced.
