### ISSUE TITLE
Conditional Breaking Changes date range should be limited based on the org's retention 

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#574]
<img width="1447" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/646b6e04-b67e-4c37-869c-b3eab33f9878">

Here the input (30 days), should be linked to the maximum retention period and show some information (in terms of an error message), when trying to set the value higher than the actual retention period.

**Comment by PlayAnyData** [comment]
Hey, I have stumbled upon this and was wondering, how we can increase the retention time, as we are self-hosting and would like to have e.g. 90 days. However, as it stands, we can only save 7, which is a very low number given that our business is driven periodically over the year, having high seasonal changes.

I can see here, it is the default retention for "FREE" plans: https://github.com/kamilkisiela/graphql-hive/blob/6e8b7aba0b48a9b63199bed4bc49953e5f750be3/packages/web/app/src/components/target/explorer/provider.tsx#L57 However, the UI is still showing 30 days initially, which is not consistent. And a message that values over 30 are not supported.

**Comment by kamilkisiela** [comment]
Fixed
