### ISSUE TITLE
Feature Request: Sorting of Fields

### ISSUE THREAD

**Issue by JoJ123-SE** [kamilkisiela/graphql-hive#583]
As a user of GraphQL HIVE, 
that is having a **public** GraphQL API with mostly anonymous operations
I want to be able to sort the fields in the **Explorer** Tab by query count.

With a public GraphQL API, the operations tile is not really helpfull:
![image](https://user-images.githubusercontent.com/87361156/199466201-561494c3-549a-4e29-bd84-67af32670e2f.png)

What we are interessted in is the following informations based on a time selection:
- What is the most used _Root Query / Root Mutation_?
- What is the most used Field of my Queries? Displayed like _"Me.id" 100 queries_
   - Optional splitted by the path, as Type A could be fetched over multiple different paths.
   - Example: _"Me.id" 90 queries_ & _"Organization.users.id" 10 queries_
- Which fields were not used in the selected timeframe?
- ... 

Probably this list can grow with the input of other Public API users. It's just a first idea.

---
So the easiest solution for us would be that you add sorting on the **Explorer Page**
For the future it could be interessting to have predefined lists like you have for Operations at the moment.

---

Another idea for visualization of the field usage could a combination of GraphQL Voyager and GraphQL Hive.
Bold Lines --> High Usage
Thin Lines --> Small Usage
Dotted Lines --> Zero Usage

Hovering a line could show more details.

**Comment by JoJ123-SE** [comment]
@kamilkisiela Do you think that something like this could be added in the near future?

**Comment by kamilkisiela** [comment]
There's no plan for it, but we want to revamp the explorer page and sorting by usage is actually nice to implement.
