### ISSUE TITLE
Request Logging

### ISSUE THREAD

**Issue by rperryng** [kamilkisiela/graphql-hive#593]
Could the `graphql-hive` server instances log their requests?  status code, runtime, information about the caller, e.g. adding something like https://github.com/mgcrea/fastify-request-logger ?  Currently I'm just using raw timestamps to try and correlate logs from client requests to the instance that I'm hosting

**Comment by kamilkisiela** [comment]
We might move away from `fastify` soon, but it could be opt-in, yes. You want to create a PR?

**Comment by rperryng** [comment]
If `graphql-hive` is moving away from `fastify` then a new logger must be sourced as well right?

Perhaps you would consider using a logger that can support shipping logs to logstash? :)
