### ISSUE TITLE
Failed to publish Schema on Self-Hosted Hive

### ISSUE THREAD

**Issue by bwoody3142** [kamilkisiela/graphql-hive#619]
I can publish to the schema registry just fine when working on the hosted version of Hive, but when switched over to the self-hosted version, I am getting this error. 

```
> hive schema:publish ./hive-schemas/airport-orgs.graphql --service airport-orgs --url http://localhost:4001/graphql --token c60e721955b423693c81aaf13949e6d3

✖ Failed to publish schema
 ›   Error: Invalid token provided!
 ›   Reference: ef938e67-8c02-45a4-aaaa-db6f9cd8384b
```

Is it even necessary to still send a token over for the self hosted version?

**Comment by jfr992** [comment]
did you solve this?

**Comment by dotansimha** [comment]
@jfr992 are you experiencing a similar issue? can you please share more details in a new issue? I'm asking because this issue seems outdated.

**Comment by jfr992** [comment]
Im experiencing the same issue:
After a while trying to publish a schema it fails with:

root@hive-server-deploy-78c986dff5-cjjbv:/tmp/schema# pnpm hive schema:publish ./schema.graphql




✖ Failed to publish schema
 ›   Error: Invalid token provided
 ›   Reference: 2uU7kflMTASUGBJi8VQP+w/0000000013
 

  path: undefined,
  locations: undefined,
  extensions: [Object: null prototype] {}
}
TRPCClientError: Unexpected token u in JSON at position 0
    at TRPCClientError.from (file:///usr/src/app/index.js:180692:12)
    at file:///usr/src/app/index.js:181018:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  message: 'Invalid token provided',
  path: [ 'schemaPublish' ],
  locations: [ { line: 2, column: 3 } ],
  extensions: [Object: null prototype] {}
}
TRPCClientError: Unexpected token u in JSON at position 0
    at TRPCClientError.from (file:///usr/src/app/index.js:180692:12)
    at file:///usr/src/app/index.js:181018:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  message: 'Invalid token provided',
  path: undefined,
  locations: undefined,
  extensions: [Object: null prototype] {}
}

**Comment by dotansimha** [comment]
> Im experiencing the same issue: After a while trying to publish a schema it fails with:
> 
> root@hive-server-deploy-78c986dff5-cjjbv:/tmp/schema# pnpm hive schema:publish ./schema.graphql
> 
> ✖ Failed to publish schema › Error: Invalid token provided › Reference: 2uU7kflMTASUGBJi8VQP+w/0000000013
> 
> path: undefined, locations: undefined, extensions: [Object: null prototype] {} } TRPCClientError: Unexpected token u in JSON at position 0 at TRPCClientError.from (file:///usr/src/app/index.js:180692:12) at file:///usr/src/app/index.js:181018:30 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { message: 'Invalid token provided', path: [ 'schemaPublish' ], locations: [ { line: 2, column: 3 } ], extensions: [Object: null prototype] {} } TRPCClientError: Unexpected token u in JSON at position 0 at TRPCClientError.from (file:///usr/src/app/index.js:180692:12) at file:///usr/src/app/index.js:181018:30 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { message: 'Invalid token provided', path: undefined, locations: undefined, extensions: [Object: null prototype] {} }

Did you configure the CLI to use your local running instance? check this page: https://the-guild.dev/graphql/hive/docs/self-hosting/client-and-cli-configuration#configuring-the-cli
