### ISSUE TITLE
track schema/cdn artifact sizes on dashboard

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#621]
CF KV has a size limit of 25MB - it would be good to know when we get closer to that number and can find a solution for allowing bigger artifact sizes :)

**Comment by kamilkisiela** [comment]
Let’s use Prometheus and the current setup we have, since it’s all managed within the GraphQL API space anyway.

**Comment by n1ru4l** [comment]
I don't think we need this anymore with https://github.com/kamilkisiela/graphql-hive/issues/622
