### ISSUE TITLE
Use R2 to store artifacts (cdn)

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#622]
instead of KV (limit of 25MB per value)

**Comment by n1ru4l** [comment]
https://github.com/kamilkisiela/graphql-hive/issues/544 is slightly related.

I am currently investigating how we can expose the artifacts via the server instance - by mirroring them in Postgres (see https://github.com/kamilkisiela/graphql-hive/issues/544#issuecomment-1303180344 for a full breakdown).

However, I am unsure whether storing all the artifacts within Postgres is a good choice for the future of Hive.
I would prefer to avoid piping (potentially huge) binary data from postgres through the Node.js server to the client.

On Cloudflare workers, the KV/R2 to client piping through a worker might not be that resource sensitive - but for a Node.js server with a single thread, it can certainly become a bottleneck.

I have the following alternative Idea:

We could change the storage to be fully based on R2, which is S3 compatible, and thus also replaceable with [Minio](https://min.io/) for the community (self-hosted) version of GraphQL Hive.

We can avoid piping the file through Node.js/CF Workers by [generating a pre-signed URL](https://developers.cloudflare.com/r2/data-access/s3-api/presigned-urls/) and then redirecting the client to that presigned URL.


```mermaid
sequenceDiagram;
    participant Client
    participant Node
    participant R2/S3

Client->>Node: Request GET /artifact/:id

  Node->>Node: Validates Access Token
  Node->>Node: Generates pre-signed URL for artifact
Node->>Client: Send redirect (302) to pre-signed URL
Client->>R2/S3: GET: Access artifact via pre-signed URL
R2/S3->>Client: Yo here is ya artifact
```

**Comment by n1ru4l** [comment]
Related https://github.com/kamilkisiela/graphql-hive/issues/544

**Comment by rickbijkerk** [comment]
My 2 cents:
Im not sure if moving away from postgres is needed for performance concerns. If im not mistaken the operation of retrieving a big resource from a db is rather IO intensive as opposed to CPU intensive, which is the thing that Node.js is good at. (https://bytearcher.com/articles/io-vs-cpu-bound/,  https://stackoverflow.com/questions/60595131/what-is-the-difference-between-cpu-intensive-and-i-o-intensive)

**Comment by kamilkisiela** [comment]
I guess the goal is to align it with the cloud setup and be able to share code.

Supergraph is stored in Cloudflare KV storage now, but we want to migrate to R2 (S3) because of size limits. It means that we need an alternative for self-hosted solution, that's why we consider using Minio.

With PostgreSQL, we would have to maintain schema, do migrations etc. Not ideal. Deploying another docker image (next to ClickHouse) is not that problematic to be honest.
