### ISSUE TITLE
exposing standard introspection results 

### ISSUE THREAD

**Issue by saihaj** [kamilkisiela/graphql-hive#667]
Hive Registry does support getting the schema SDL using `CDN_URL/sdl` learn more here: https://docs.graphql-hive.com/features/registry-usage#single-schema-project 

But it fails to work with GraphQL Codegen
![CleanShot 2022-11-22 at 10 05 52](https://user-images.githubusercontent.com/44710980/203348686-7ddf8995-37e2-4f5d-83e8-6e5ac8ea8ab7.png)

**Comment by saihaj** [comment]
when doing `/introspection`
![CleanShot 2022-11-22 at 10 08 31](https://user-images.githubusercontent.com/44710980/203349407-cc1e1fb4-6870-4f94-a903-27de3c6ad9ff.png)

**Comment by n1ru4l** [comment]
I am unsure whether we should expose introspection - introspection is dynamic, so we would need to build and serve the whole schema on an ad-hoc basis. This could be a potential performance degradation in case some of the users have huge schemas.

In https://github.com/kamilkisiela/graphql-hive/pull/692 we are introducing a static SDL endpoint that is stored on S3/R2.

**Comment by kamilkisiela** [comment]
We won't support introspection result for the reasons @n1ru4l mentioned, but #692 added support for `.graphql` and `.graphqls` extensions, so `/sdl` should be now doable.
