### ISSUE TITLE
Allow to download schema via CLI

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#678]
- [ ] full schema
- [ ] supergraphsdl
- [ ] introspection result
- [ ] schema of a service

**Comment by kamilkisiela** [comment]
#622 will help a lot here

**Comment by n1ru4l** [comment]
For now everyone struggling with this can download the schema from CDN:

```
curl -L -H 'X-Hive-CDN-Key: <your-cdn-key>' https://cdn.graphql-hive.com/artifacts/v1/<your-target-id>/sdl.graphql

**Comment by dotansimha** [comment]
@n1ru4l @kamilkisiela  should we just close this one? Or do we want to eventually have that as part of the CLI commands?

**Comment by kamilkisiela** [comment]
Definitely as part of the CLI, for convenience

**Comment by n1ru4l** [comment]
See https://github.com/kamilkisiela/graphql-hive/pull/1541
