### ISSUE TITLE
Apollo Federation v2 schema composition

### ISSUE THREAD

**Issue by jereckley** [kamilkisiela/graphql-hive#712]
Version 2 of gateway has some cool changes but it doesn't seem to be supported in Hive.

Example: Extending types is not required -> https://www.apollographql.com/docs/federation/federation-2/new-in-federation-2#originating-subgraphs but in hive composition fails if type is not extended.

I'd love some feedback, maybe i'm missing something or is this planned work (ETA?). Thanks!

**Comment by jereckley** [comment]
It looks like this is already in the works -> https://github.com/kamilkisiela/graphql-hive/pull/702 .

**Comment by kamilkisiela** [comment]
Federation V2 is available only when using https://docs.graphql-hive.com/features/external-schema-composition.
We plan to support it natively at some point.

**Comment by jereckley** [comment]
Thank you @kamilkisiela for the feedback . If we needed to use V2 in 6 months. Would you suggest we work towards implementing our own external composition or just waiting?

**Comment by dotansimha** [comment]
> Thank you @kamilkisiela for the feedback . If we needed to use V2 in 6 months would you suggest we work towards implementing our own external composition or just waiting?

At the moment we recommend to use the external composition. You can deploy very easily and quickly as Docker image, or as CloudFlare Worker. 
You can find the documentation here: https://docs.graphql-hive.com/features/external-schema-composition#apollo-federation-v2-example 
I think @n1ru4l also wanted to create a simple Docker image for it?

**Comment by n1ru4l** [comment]
My plan is to also record a video on how to set this up next week.
