### ISSUE TITLE
Race condition in the schema publishing flow

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#728]
## Problem 

Every new version inherits commits from a previous version (all when a new version introduces a new service, and all except one when an already existing service gets updated).

One of our customers reported an inconsistency. I checked and here's the timeline of versions:

```
version 1   c_1
version 2   c_1  c_2
version 3   c_1  c_2  c_3
version 4   c_1  c_2  c_3  c_4
version 5   c_1  c_2  c_3  c_4  c_5
version 6   c_1   ?   c_3  c_4       c_6
version 7   c_1  c_2  c_3  c_4        ?   c_7
version 8   c_1       c_3  c_4       c_6      c_8
version 9   c_1       c_3  c_4       c_6      c_8  c_9
```

To me, it looks like 2 versions published at the same time were competing with each other and persisted an incorrect state.

## Proposed solution

The flow should be something like this.
1. An attempt to publish a new schema
1. Validate the token, access etc.
1. If another attempt to publish the schema is already in progress, wait for it to complete (regardless the status - failure or success)
1. Continue with the regular flow.

We need a FIFO queue but grouped by target's id.

Why? Because we don’t want it to block the entire queue. For every "publish" action, only actions related to the same target should be executed one by one, first in, first out.

Context: https://tortilla-hq.slack.com/archives/C01E8ATBQGN/p1669909867184569?thread_ts=1669908661.254419&cid=C01E8ATBQGN

**Comment by kamilkisiela** [comment]
It's also an opportunity to improve [https://github.com/kamilkisiela/graphql-hive/blob/3b073ad8f4fcfe57462783bb18c8ecad[…]s/services/api/src/modules/schema/providers/schema-publisher.ts](https://github.com/kamilkisiela/graphql-hive/blob/3b073ad8f4fcfe57462783bb18c8ecad0d57e31e/packages/services/api/src/modules/schema/providers/schema-publisher.ts#L202-L207).
It's there to share the execution of the schema publish flow, to prevent running the flow multiple times across many replicas.

**Comment by n1ru4l** [comment]
## Idea Proposal: Reject publishes; push responsibilty to client

- Reject schema publishes if one publish is already in progress (use a [distributed lock](https://redis.io/docs/manual/patterns/distributed-locks/))
- Push responsibility of retrying publish after rejection to the client

### Pros

- Minimal effort for implementation (no complex queue system and long-running HTTP requests)

### Cons

- Breaks how the schema publish flow works currently
- Requires people to upgrade the hive CLI

**Comment by n1ru4l** [comment]
## Idea Proposal: Redis lock; Keep publish connection alive

- Accept schema publish requests as before
- Try to acquire lock and retry acquiring the lock in intervals
- Once the lock is acquired, run the logic

## Pros

- Minimal effort for implementation
- Does not break the existing schema publish flow
- No Hive CLI upgrade required

## Cons

- HTTP timeout
- more Node.js memory pressure 😅
