### ISSUE TITLE
Github schema check integration 

### ISSUE THREAD

**Issue by klippx** [kamilkisiela/graphql-hive#750]
We have a federated setup in a monorepo consisting of several subgraphs, and for each subgraph and each target we do a 

```sh
yarn hive schema:check --service $service "${service}/schema.gql" --github
```

The problem with the github integration is that it has a hardcoded name `GraphQL Hive / GraphQL Hive - schema:check` when we need one for each subgraph and target:
```
Hive - schema:check: dgs1@production - success ✅
Hive - schema:check: dgs1@staging - success ✅
Hive - schema:check: dgs2@production - failed ⛔️
Hive - schema:check: dgs2@staging - failed ⛔️
```

As it stands right now a breaking change does not show up as it is overwritten by another successful subgraph check.

**Comment by kamilkisiela** [comment]
Makes sense

**Comment by n1ru4l** [comment]
I think https://github.com/kamilkisiela/graphql-hive/pull/751 should fix it
