### ISSUE TITLE
Feature Request: Deep link to query in Laboratory

### ISSUE THREAD

**Issue by klippx** [kamilkisiela/graphql-hive#767]
_"As a Hive user, when I author a query in Laboratory, I would like to be able to share my query as a link (including variables and headers) with another Hive user."_

The reason for this is that we then allow people to describe their problem in our supergraph support channel and include a link to the problematic query in question (likely as http deep link to the Hive Laboratory). The support can then get exactly the same state as the reporter and see what she sees when we debug and support our consumers.

This is an extremely powerful feature that will enable efficient issue resolution for the federated support channel that I think the community would love to see as part of the core Hive product. I think it would also useful for smaller/simpler graph setups as well.

**Comment by klippx** [comment]
I just realized that since you only return mock data you might not understand why this feature is important. But this is assuming you can actually get _real_ data out of the Laboratory; https://github.com/kamilkisiela/graphql-hive/issues/788

**Comment by n1ru4l** [comment]
Closing this, as it is already possible to share links to documents
