### ISSUE TITLE
need to fix width so there is no scrollbar on x-axis

### ISSUE THREAD

**Issue by saihaj** [kamilkisiela/graphql-hive#771]
![CleanShot 2022-12-08 at 16 55 09](https://user-images.githubusercontent.com/44710980/206575752-2b09a5fb-9706-4554-8a6b-d65511b59f3e.png)

![CleanShot 2022-12-08 at 16 51 39](https://user-images.githubusercontent.com/44710980/206575074-11a21eec-47e8-4260-af9b-29254d97b56d.gif)

**Comment by dotansimha** [comment]
seems to be fixed already?

**Comment by kamilkisiela** [comment]
It's still there

**Comment by B2o5T** [comment]
couldn't reproduce ☹️

**Comment by kamilkisiela** [comment]
See the screenshots that @saihaj attached. Create a project in an organization and the scrollbar will appear
