### ISSUE TITLE
Client SDK fetcher uses `/schema`, new endpoint is `/services`

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#777]
https://github.com/kamilkisiela/graphql-hive/blob/4e3a8d42dd69ea4fd2fb3d2bc0691778d81829fd/packages/libraries/client/src/gateways.ts#L33

The fetcher will currently fail when used with the new artifacts endpoint.

We have the following solutions:

1. add an alias for `/schema` -> `/services` on new artifacts CDN endpoint
2. add an alias for `/schema` -> `/services` on the old CDN endpoint + update the SDK to use `/schema`
3. Create a URL check within the SDK (string contains `/artifacts/v1`) for determining whether to append `/schema` or `/services`

Option 2 seems like the best solution to me, as it does not require adding unnecessary aliases on the new endpoint and allows us to immediately update the SDK, without legacy logic.

**Comment by Ceres6** [comment]
Hi! I was having the same problem and I was lucky to find this open issue. The docs still refer to the outdated `/shema` endpoint and is quite confusing for new people to get a `Not found` for that one. Maybe that could be updated as well.

**Comment by n1ru4l** [comment]
@Ceres6 sorry for the inconvenience! I am gonna take care of this :)
