### ISSUE TITLE
stuck in create project screen

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#784]
Reproduction:

1. Fill in project name
2. Select Custom
3. Fill in invalid validtaion endpoint
4. Select Federation
5. Try to submit form
6. Nothing happens

<img width="692" alt="image" src="https://user-images.githubusercontent.com/14338007/207021528-f72994e0-55ee-47f6-93bd-c2e99d2d343e.png">

**Comment by kamilkisiela** [comment]
We no longer support `Custom`
