### ISSUE TITLE
Improve instructions and interactivity for CDN modal

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#786]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3680083/207031241-ab150ce5-31f2-4173-93a9-c733124787c4.png">

Things to improve:
- A dropdown/something else with ready-to-use code examples for different gateways
- examples for all available endpoints
- `curl` for fetching the schemas
- interactive example for using the schema with different tools (codegen)

**Comment by n1ru4l** [comment]
YES YES YES
