### ISSUE TITLE
Laboratory: Query actual graph endpoints

### ISSUE THREAD

**Issue by klippx** [kamilkisiela/graphql-hive#788]
In Laboratory today you can only see mock data based on schema types. That misses the central point for us, we need to see real data.

So for example, I have set up my Hive account with two targets: One for staging and another for production. When I am in Laboratory and write a query, I expect it to be sent to a configured endpoint for that target; such as for the staging target I want the query/variables/headers sent toward the staging gateway. 

When I execute a query I want it to be sent to that endpoint and see the result resolving _real_ data. I don't want to look at mock data.

**Comment by dotansimha** [comment]
That's a super interesting issue @klippx , thank you for reporting this one. 
At the moment we provide a mocked API in the Lab (mainly for exploration and documentation purposes). 

I think at the moment we don't really have the gateway URL (we only store service(s) URLs for projects like Federation or Stitching), so we are not able to send the requests to the actual service. 
@kamilkisiela do you think we can allow sending the runtime URL (of either the gateway or the single-project endpoint) and then use that in the Lab?

**Comment by dotansimha** [comment]
An update on this one; we now have the persisted SDL of every schema published, so this makes it easier to have access to the real latest composable schema. This means we are able to use that as introspection. The missing piece is to allow users to specify a runtime URL per target, and then allow to switch between mocked/actual endpoints in the Lab.

**Comment by kamilkisiela** [comment]
I think we can do the following:
- a form in target's settings to provide an url of a real endpoint and a list of secrets (accessible in GraphiQL - header values)
- a note on top of GraphiQL: "Connect it with your real GraphQL endpoint" or "Executing operations against real GraphQL API".
- inject secrets in header's value
