### ISSUE TITLE
OIDC: Logging in to corporate ID results in an invalid redirect URL

### ISSUE THREAD

**Issue by BasvanGrinsven** [kamilkisiela/graphql-hive#806]
Hi all,

First of all, major thanks for adding OIDC support. 
I've been messing around a bit to integrate our identity provider with OIDC through AWS Cognito.

When I navigate to the URL that you provide in `Manage OpenID Connect Integration` I get the pop-up to login to the corporate ID.
Looking at the URL, everything looks fine. However, when I navigate to the corporate ID login, I get redirected to an invalid URL.
Supertokens uses the `state` parameter in the URL to prevent CSRF. When I navigate to the corporate login, the `state` parameter is no longer URL encoded and contains `||` instead of `%7C%7C`. Changing this manually will result in the correct navigation to the corporate login.

If you need more information, please reach out.

Thanks!

**Comment by n1ru4l** [comment]
This seems to be related to this file, the parameter needs to be properly URL encoded:

https://github.com/kamilkisiela/graphql-hive/blob/main/packages/web/app/src/lib/supertokens/third-party-email-password-react-oidc-provider.ts

**Comment by dotansimha** [comment]
@n1ru4l should we just escape the values in https://github.com/kamilkisiela/graphql-hive/blob/main/packages/web/app/src/lib/supertokens/third-party-email-password-react-oidc-provider.ts#L58 ?
