### ISSUE TITLE
Ability to create user specific hook in Hive

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#832]
Is it possible for GraphQL Hive to notify 3rd party app (e.g. via hook or any other REST/GraphQL request) that e.g. a new version of schema was published? E.g. we want schema to be refreshed with that is just stored in the Hive.

I know we can define an alert/notification for GitHub + Slack. But what about e.g. a production service? We don't want do this e.g. via Slack (as a proxy).

**Comment by dotansimha** [comment]
Hi @cookieMr! 

When you create an alert target, you have the option to select the `Webhook` type: 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/3680083/208445693-e5044998-3253-4f35-92ae-5e7914df6dd8.png">

After that, you'll be able to create a specific alert of type `Schema Change Notifications` for that channel.

**Comment by cookieMr** [comment]
Thx @dotansimha 

Plz, close this issue to keep your backlog clean.

**Comment by kamilkisiela** [comment]
Here's the shape of the payload

https://github.com/kamilkisiela/graphql-hive/blob/137c9ae2c63e99bc5926baab4e20c14412e46d25/packages/services/api/src/modules/alerts/providers/adapters/common.ts#L11-L28
