### ISSUE TITLE
Disable SSR

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#839]
- move auth guard to client

**Comment by dotansimha** [comment]
Closing this one, as we seem to depend more on SSR (redirects, auth and so on)

**Comment by kamilkisiela** [comment]
But we shouldn't

**Comment by kamilkisiela** [comment]
The UX sucks because of SSR. When switching between pages, we do an extra http call before transitioning from one page to another

**Comment by kamilkisiela** [comment]
#4288
