### ISSUE TITLE
Self-hosted: Connecting to CDN from gateway failed (using `createSupergraphManager`) 

### ISSUE THREAD

**Issue by Huljo** [kamilkisiela/graphql-hive#905]
Trying to connect my gateway to a self-hosted instance following [this doc](https://docs.graphql-hive.com/features/registry-usage#apollo-federation)
````typescript
const gateway = new ApolloGateway({
    supergraphSdl: createSupergraphManager({
      endpoint: "http://localhost:8082/artifacts/v1/8c4fc5d5-54ba-4431-9cac-31a9a178543d",
      key: "[REDACTED]",
      pollIntervalInMs: 15_000
    })
  });

const server = new ApolloServer({
  gateway
})

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`)
})
````
Error while running the server : 
````
'Body must be a string. Received: { initialize: [function initialize] }.'
````

**Comment by dotansimha** [comment]
Thanks for reporting it, @Huljo! 

What Docker tag are you using?

**Comment by Huljo** [comment]
Hi @dotansimha 
Im using tag https://github.com/kamilkisiela/graphql-hive/commit/065a699ce8324c36525b95ece37f870935d86efd

**Comment by dotansimha** [comment]
Thanks @Huljo , are you able to try to update to latest (or, you can try to use `cb1aac0f9b4f24c7e64d6049fbf83b54cbe111a6` which is the latest we have deployed on the SaaS of Hive)  
I think we've pushed a few more fixes for the self-hosted CDN, so it might be related to the issue you are having?

**Comment by n1ru4l** [comment]
Hey @Huljo, can upu make sure uou use the latest docker-compose.community.yml version + @apollo/server?

I tried to reproduce you issue without success on an integration test in https://github.com/kamilkisiela/graphql-hive/pull/988

**Comment by n1ru4l** [comment]
@Huljo Did you provide a proper (non-empty sting) `CDN_AUTH_PRIVATE_KEY` environment variable to the container?

https://github.com/kamilkisiela/graphql-hive/blob/5e6afbfd3fce1a85586e2c9d4f40bf649951170a/docker-compose.community.yml#L249

**Comment by n1ru4l** [comment]
Hey @Huljo any update?

**Comment by Huljo** [comment]
Hello @n1ru4l Sorry for the delay. 

This key is empty on my side. (`CDN_AUTH_PRIVATE_KEY: ''` ) I removed it since I'm not using a CDN at the moment. Is it mandatory ? 

Thanks

**Comment by n1ru4l** [comment]
It is no longer needed in the latest version from `main`.

**Comment by n1ru4l** [comment]
Note that you are using the "local" CDN when you access "http://localhost:8082/artifacts/v1/8c4fc5d5-54ba-4431-9cac-31a9a178543d","

**Comment by n1ru4l** [comment]
Closing this as it seems it is resolved.
