### ISSUE TITLE
Self hosted version - no connect button

### ISSUE THREAD

**Issue by alanquigley-toast** [kamilkisiela/graphql-hive#956]
Based on using the SaaS version and watching the self-hosted install video, I was expecting to see a connect button?

Are there further steps required to setup the storage to allow clients to connect to the self-hosted version?

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/54547753/210832309-a750f7b5-e0cc-4324-813d-aed139fbcefd.png">

**Comment by dotansimha** [comment]
@n1ru4l I think this might be a bug, or invalid env vars configuration?

**Comment by alanquigley-toast** [comment]
I used the out of the box env vars from the guide - do I need to specific env vars for a local CDN container maybe. Anything I can do to help just ask :)

**Comment by alanquigley-toast** [comment]
This was a mistake on my side, I copied the env vars directly from the guide into the .env file.
