### ISSUE TITLE
Consider to drop the default personal organization 

### ISSUE THREAD

**Issue by dotansimha** [kamilkisiela/graphql-hive#98]
The personal organization seems to be unused in most cases, and people prefer to create orgs for companies/groups.
Maybe we should show the org creation wizard when there are no orgs at all for the user? 

@kamilkisiela @B2o5T what do you think?

**Comment by kamilkisiela** [comment]
👍🏻

**Comment by n1ru4l** [comment]
One more argument for removing it as it introduces confusion https://github.com/kamilkisiela/graphql-hive/issues/1160
